namespace GAS.Runtime
{
    public static partial class HeadlessAutoChessScenario
    {
        private static UnitDefinition[] CreateDefaultUnits()
        {
            return new[]
            {
                new UnitDefinition(
                    "player-guardian",
                    HeadlessAutoChessTeam.Player,
                    slot: 0,
                    boardX: 1,
                    boardY: 1,
                    turnOrder: 0,
                    health: 72f,
                    mana: 0f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    supportAbilityCode: AbilityPlayerBarrier,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain,
                    equipmentGameplayEffectCode: GameplayEffectPlayerCounterGear,
                    counterDamageGameplayEffectCode: GameplayEffectPlayerCounterDamage),
                new UnitDefinition(
                    "player-mage",
                    HeadlessAutoChessTeam.Player,
                    slot: 1,
                    boardX: 0,
                    boardY: 0,
                    turnOrder: 1,
                    health: 54f,
                    mana: 3f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: AbilityPlayerManaBurst,
                    manaAbilityThreshold: 3f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    controlAbilityCode: AbilityPlayerControlStun,
                    controlTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    supportAbilityCode: AbilityPlayerBarrier,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    synergyCode: SynergyArcane,
                    synergyThreshold: SynergyArcaneThreshold,
                    synergyAllyBuffGameplayEffectCode: GameplayEffectArcaneTeamBuff,
                    synergyEnemyDebuffGameplayEffectCode: GameplayEffectArcaneStormDebuff,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain,
                    equipmentGameplayEffectCode: GameplayEffectPlayerCounterGear,
                    counterDamageGameplayEffectCode: GameplayEffectPlayerCounterDamage,
                    initialHealth: 52f),
                new UnitDefinition(
                    "player-ranger",
                    HeadlessAutoChessTeam.Player,
                    slot: 2,
                    boardX: 0,
                    boardY: 2,
                    turnOrder: 2,
                    health: 50f,
                    mana: 0f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    supportAbilityCode: AbilityPlayerCleanse,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    summonAbilityCode: AbilityPlayerSummon,
                    maxActiveSummons: PlayerSummonMaxActiveCount,
                    synergyCode: SynergyArcane,
                    synergyThreshold: SynergyArcaneThreshold,
                    synergyAllyBuffGameplayEffectCode: GameplayEffectArcaneTeamBuff,
                    synergyEnemyDebuffGameplayEffectCode: GameplayEffectArcaneStormDebuff,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain,
                    equipmentGameplayEffectCode: GameplayEffectPlayerCounterGear,
                    counterDamageGameplayEffectCode: GameplayEffectPlayerCounterDamage,
                    initialHealth: 46f),
                new UnitDefinition(
                    "enemy-brute",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 0,
                    boardX: 4,
                    boardY: 1,
                    turnOrder: 3,
                    health: 44f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    arcaneResistance: EnemyArcaneResistance),
                new UnitDefinition(
                    "enemy-rogue",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 1,
                    boardX: 5,
                    boardY: 0,
                    turnOrder: 4,
                    health: 36f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    arcaneResistance: EnemyArcaneResistance),
                new UnitDefinition(
                    "enemy-shaman",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 2,
                    boardX: 5,
                    boardY: 2,
                    turnOrder: 5,
                    health: 34f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    controlAbilityCode: AbilityPlayerControlStun,
                    controlTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    reviveGameplayEffectCode: GameplayEffectSelfRevive,
                    maxReviveCount: 1,
                    arcaneResistance: EnemyArcaneResistance),
            };
        }

        private static UnitDefinition[] CreatePlayerAdvantageUnits()
        {
            var units = CreateDefaultUnits();
            units[0] = units[0].WithStats(84f, 1f);
            units[1] = units[1].WithStats(62f, 3f);
            units[2] = units[2].WithStats(58f, 1f);
            units[3] = units[3].WithStats(36f, 0f);
            units[4] = units[4].WithStats(30f, 0f);
            units[5] = units[5].WithStats(28f, 0f);
            return units;
        }

        private static UnitDefinition[] CreateEnemyPressureUnits()
        {
            var defaultUnits = CreateDefaultUnits();
            var units = new UnitDefinition[defaultUnits.Length + 1];
            for (var i = 0; i < defaultUnits.Length; i++)
                units[i] = defaultUnits[i];

            units[0] = units[0].WithStats(66f, 0f);
            units[1] = units[1].WithStats(48f, 3f);
            units[2] = units[2].WithStats(26f, 0f);
            units[3] = units[3].WithStats(50f, 0f);
            units[4] = units[4].WithStats(42f, 0f);
            units[5] = units[5].WithStats(38f, 0f);
            units[6] = new UnitDefinition(
                "enemy-vanguard",
                HeadlessAutoChessTeam.Enemy,
                slot: 3,
                boardX: 4,
                boardY: 0,
                turnOrder: 6,
                health: 28f,
                mana: 0f,
                primaryAbilityCode: AbilityEnemyStrike,
                manaAbilityCode: 0,
                manaAbilityThreshold: 0f,
                primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                arcaneResistance: EnemyArcaneResistance);
            return units;
        }

        private static UnitDefinition[] CreateLargeBoardUnits()
        {
            return new[]
            {
                new UnitDefinition(
                    "player-guardian",
                    HeadlessAutoChessTeam.Player,
                    slot: 0,
                    boardX: 1,
                    boardY: 1,
                    turnOrder: 0,
                    health: 82f,
                    mana: 0f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    supportAbilityCode: AbilityPlayerBarrier,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain,
                    equipmentGameplayEffectCode: GameplayEffectPlayerCounterGear,
                    counterDamageGameplayEffectCode: GameplayEffectPlayerCounterDamage),
                new UnitDefinition(
                    "enemy-brute",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 0,
                    boardX: 4,
                    boardY: 1,
                    turnOrder: 1,
                    health: 44f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    arcaneResistance: EnemyArcaneResistance),
                new UnitDefinition(
                    "player-mage",
                    HeadlessAutoChessTeam.Player,
                    slot: 1,
                    boardX: 0,
                    boardY: 0,
                    turnOrder: 2,
                    health: 58f,
                    mana: 3f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: AbilityPlayerManaBurst,
                    manaAbilityThreshold: 3f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    controlAbilityCode: AbilityPlayerControlStun,
                    controlTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    supportAbilityCode: AbilityPlayerBarrier,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    synergyCode: SynergyArcane,
                    synergyThreshold: SynergyArcaneThreshold,
                    synergyAllyBuffGameplayEffectCode: GameplayEffectArcaneTeamBuff,
                    synergyEnemyDebuffGameplayEffectCode: GameplayEffectArcaneStormDebuff,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain,
                    equipmentGameplayEffectCode: GameplayEffectPlayerCounterGear,
                    counterDamageGameplayEffectCode: GameplayEffectPlayerCounterDamage),
                new UnitDefinition(
                    "enemy-rogue",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 1,
                    boardX: 5,
                    boardY: 0,
                    turnOrder: 3,
                    health: 36f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    arcaneResistance: EnemyArcaneResistance),
                new UnitDefinition(
                    "player-ranger",
                    HeadlessAutoChessTeam.Player,
                    slot: 2,
                    boardX: 0,
                    boardY: 2,
                    turnOrder: 4,
                    health: 52f,
                    mana: 0f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    supportAbilityCode: AbilityPlayerCleanse,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    summonAbilityCode: AbilityPlayerSummon,
                    maxActiveSummons: PlayerSummonMaxActiveCount,
                    synergyCode: SynergyArcane,
                    synergyThreshold: SynergyArcaneThreshold,
                    synergyAllyBuffGameplayEffectCode: GameplayEffectArcaneTeamBuff,
                    synergyEnemyDebuffGameplayEffectCode: GameplayEffectArcaneStormDebuff,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain,
                    equipmentGameplayEffectCode: GameplayEffectPlayerCounterGear,
                    counterDamageGameplayEffectCode: GameplayEffectPlayerCounterDamage),
                new UnitDefinition(
                    "enemy-shaman",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 2,
                    boardX: 5,
                    boardY: 2,
                    turnOrder: 5,
                    health: 34f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    controlAbilityCode: AbilityPlayerControlStun,
                    controlTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    reviveGameplayEffectCode: GameplayEffectSelfRevive,
                    maxReviveCount: 1,
                    arcaneResistance: EnemyArcaneResistance),
                new UnitDefinition(
                    "player-cleric",
                    HeadlessAutoChessTeam.Player,
                    slot: 3,
                    boardX: 1,
                    boardY: 0,
                    turnOrder: 6,
                    health: 58f,
                    mana: 1f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    synergyCode: SynergyArcane,
                    synergyThreshold: SynergyArcaneThreshold,
                    synergyAllyBuffGameplayEffectCode: GameplayEffectArcaneTeamBuff,
                    synergyEnemyDebuffGameplayEffectCode: GameplayEffectArcaneStormDebuff,
                    supportAbilityCode: AbilityPlayerBarrier,
                    supportTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain),
                new UnitDefinition(
                    "enemy-vanguard",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 3,
                    boardX: 4,
                    boardY: 0,
                    turnOrder: 7,
                    health: 40f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.Frontline,
                    arcaneResistance: EnemyArcaneResistance),
                new UnitDefinition(
                    "player-battlemage",
                    HeadlessAutoChessTeam.Player,
                    slot: 4,
                    boardX: 1,
                    boardY: 2,
                    turnOrder: 8,
                    health: 56f,
                    mana: 3f,
                    primaryAbilityCode: AbilityPlayerStrike,
                    manaAbilityCode: AbilityPlayerManaBurst,
                    manaAbilityThreshold: 3f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    controlAbilityCode: AbilityPlayerControlStun,
                    controlTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    synergyCode: SynergyArcane,
                    synergyThreshold: SynergyArcaneThreshold,
                    synergyAllyBuffGameplayEffectCode: GameplayEffectArcaneTeamBuff,
                    synergyEnemyDebuffGameplayEffectCode: GameplayEffectArcaneStormDebuff,
                    killManaGainGameplayEffectCode: GameplayEffectKillManaGain),
                new UnitDefinition(
                    "enemy-archer",
                    HeadlessAutoChessTeam.Enemy,
                    slot: 4,
                    boardX: 5,
                    boardY: 1,
                    turnOrder: 9,
                    health: 32f,
                    mana: 0f,
                    primaryAbilityCode: AbilityEnemyStrike,
                    manaAbilityCode: 0,
                    manaAbilityThreshold: 0f,
                    primaryTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    manaTargetPolicy: HeadlessAutoChessTargetPolicy.LowestHealth,
                    arcaneResistance: EnemyArcaneResistance),
            };
        }
    }
}
