using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace GAS.Editor
{
    public static class LubanNormalizedRowBootstrap
    {
        private const string AbilityJson = "exgas_tbability.json";
        private const string GameplayEffectJson = "exgas_tbgameplayeffect.json";
        private const string AttributeSetJson = "exgas_tbattributeset.json";
        private const string GameplayTagJson = "exgas_tbgameplaytags.json";
        private const string GameplayCueJson = "exgas_tbgameplaycue.json";
        private const string TimelineAbilityJson = "exgas_tbtimelineability.json";
        private const string OutputFileName = "Editor/LubanNormalizedRows.gen.cs";

        public static string Generate(GasCodeGenSettings settings)
        {
            if (settings == null)
                throw new ArgumentNullException(nameof(settings));

            var projectRoot = GasCodeGenEnvironment.ProjectRoot;
            var outputRoot = ResolveProjectPath(projectRoot, settings.OutputPath);
            var outputPath = Path.Combine(outputRoot, OutputFileName.Replace('/', Path.DirectorySeparatorChar));
            var directory = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            var model = LubanNormalizedRowsModel.Create(projectRoot, settings);
            using var writer = new IndentedWriter(new StreamWriter(outputPath));
            WriteFile(writer, model);
            EnsureUnityMeta(outputPath);
            return outputPath;
        }

        private static void WriteFile(IndentedWriter writer, LubanNormalizedRowsModel model)
        {
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System;");
            writer.WriteLine("using System.Linq;");
            writer.WriteLine("");
            writer.WriteLine("namespace GAS.Editor");
            writer.WriteLine("{");
            writer.Indent++;
            WriteRowStructs(writer);
            WriteRowFactory(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteRowStructs(IndentedWriter writer)
        {
            writer.WriteLine("public struct AbilityDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int AbilityCode;");
            writer.WriteLine("public int Level;");
            writer.WriteLine("public int TimelineId;");
            writer.WriteLine("public int PrimaryGameplayEffectCode;");
            writer.WriteLine("public int SecondaryGameplayEffectCode;");
            writer.WriteLine("public int ActivationOwnedTagCode;");
            writer.WriteLine("public int[] ActivationRequiredAllTagCodes;");
            writer.WriteLine("public int[] ActivationRequiredAnyTagCodes;");
            writer.WriteLine("public int[] ActivationRequiredNoneTagCodes;");
            writer.WriteLine("public int[] ActivationBlockedAllTagCodes;");
            writer.WriteLine("public int[] ActivationBlockedAnyTagCodes;");
            writer.WriteLine("public int[] ActivationBlockedNoneTagCodes;");
            writer.WriteLine("public int CostGameplayEffectCode;");
            writer.WriteLine("public int CooldownGameplayEffectCode;");
            writer.WriteLine("public int CooldownFrames;");
            writer.WriteLine("public int TargetRuleCode;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");

            writer.WriteLine("public struct GameplayEffectDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int GameplayEffectCode;");
            writer.WriteLine("public string Name;");
            writer.WriteLine("public int ModifierAttributeSetCode;");
            writer.WriteLine("public int ModifierAttributeCode;");
            writer.WriteLine("public int ModifierOperation;");
            writer.WriteLine("public float ModifierMagnitude;");
            writer.WriteLine("public int ModifierMagnitudeSource;");
            writer.WriteLine("public int ModifierMagnitudeKey;");
            writer.WriteLine("public int[] ModifierAttributeSetCodes;");
            writer.WriteLine("public int[] ModifierAttributeCodes;");
            writer.WriteLine("public int[] ModifierOperations;");
            writer.WriteLine("public float[] ModifierMagnitudes;");
            writer.WriteLine("public int[] ModifierMagnitudeSources;");
            writer.WriteLine("public int[] ModifierMagnitudeKeys;");
            writer.WriteLine("public int DurationFrames;");
            writer.WriteLine("public int PeriodFrames;");
            writer.WriteLine("public int PeriodGameplayEffectCode;");
            writer.WriteLine("public int GrantedTagCode;");
            writer.WriteLine("public int GameplayCueCode;");
            writer.WriteLine("public int DamageTypeCode;");
            writer.WriteLine("public int ResistanceAttributeSetCode;");
            writer.WriteLine("public int ResistanceAttributeCode;");
            writer.WriteLine("public float ResistanceCap;");
            writer.WriteLine("public int RemoveGameplayEffectTagCode;");
            writer.WriteLine("public int[] ApplicationRequiredAllTagCodes;");
            writer.WriteLine("public int[] ApplicationRequiredAnyTagCodes;");
            writer.WriteLine("public int[] ApplicationRequiredNoneTagCodes;");
            writer.WriteLine("public int[] OngoingRequiredAllTagCodes;");
            writer.WriteLine("public int[] OngoingRequiredAnyTagCodes;");
            writer.WriteLine("public int[] OngoingRequiredNoneTagCodes;");
            writer.WriteLine("public int[] RemoveGameplayEffectAllTagCodes;");
            writer.WriteLine("public int[] RemoveGameplayEffectAnyTagCodes;");
            writer.WriteLine("public int[] RemoveGameplayEffectNoneTagCodes;");
            writer.WriteLine("public int[] ImmunityAllTagCodes;");
            writer.WriteLine("public int[] ImmunityAnyTagCodes;");
            writer.WriteLine("public int[] ImmunityNoneTagCodes;");
            writer.WriteLine("public int StackingCode;");
            writer.WriteLine("public int StackLimitCount;");
            writer.WriteLine("public int StackType;");
            writer.WriteLine("public int EffectDurationRefreshPolicy;");
            writer.WriteLine("public int EffectPeriodResetPolicy;");
            writer.WriteLine("public int EffectExpirationPolicy;");
            writer.WriteLine("public bool DenyOverflowApplication;");
            writer.WriteLine("public bool ClearStackOnOverflow;");
            writer.WriteLine("public int OverflowGameplayEffectCode;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");

            writer.WriteLine("public struct AttributeSetDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int AttributeSetCode;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");

            writer.WriteLine("public struct AttributeDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int AttributeSetCode;");
            writer.WriteLine("public int AttributeCode;");
            writer.WriteLine("public float InitialValue;");
            writer.WriteLine("public bool IsClampMin;");
            writer.WriteLine("public bool IsClampMax;");
            writer.WriteLine("public float MinValue;");
            writer.WriteLine("public float MaxValue;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");

            writer.WriteLine("public struct GameplayTagDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int GameplayTagCode;");
            writer.WriteLine("public int[] ParentCodes;");
            writer.WriteLine("public int[] ChildCodes;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");

            writer.WriteLine("public struct GameplayCueDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int GameplayCueCode;");
            writer.WriteLine("public string PresentationKey;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");

            writer.WriteLine("public struct TimelineDefinitionRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public int TimelineId;");
            writer.WriteLine("public int GameplayEffectCode;");
            writer.WriteLine("public int SecondaryGameplayEffectCode;");
            writer.WriteLine("public string TargetCatcherName;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine("");
        }

        private static void WriteRowFactory(IndentedWriter writer, LubanNormalizedRowsModel model)
        {
            writer.WriteLine("public static class GASGeneratedLubanNormalizedRows");
            writer.WriteLine("{");
            writer.Indent++;
            WriteFactory(writer, "AbilityDefinitionRow", "CreateAbilityRows", model.Abilities, WriteAbilityInitializer);
            WriteFactory(writer, "GameplayEffectDefinitionRow", "CreateGameplayEffectRows", model.GameplayEffects, WriteGameplayEffectInitializer);
            WriteFactory(writer, "AttributeSetDefinitionRow", "CreateAttributeSetRows", model.AttributeSets, WriteAttributeSetInitializer);
            WriteFactory(writer, "AttributeDefinitionRow", "CreateAttributeRows", model.Attributes, WriteAttributeInitializer);
            WriteFactory(writer, "GameplayTagDefinitionRow", "CreateGameplayTagRows", model.GameplayTags, WriteGameplayTagInitializer);
            WriteFactory(writer, "GameplayCueDefinitionRow", "CreateGameplayCueRows", model.GameplayCues, WriteGameplayCueInitializer);
            WriteFactory(writer, "TimelineDefinitionRow", "CreateTimelineRows", model.Timelines, WriteTimelineInitializer);
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteFactory<T>(
            IndentedWriter writer,
            string rowType,
            string methodName,
            IReadOnlyList<T> rows,
            Func<T, string> createInitializer)
        {
            writer.WriteLine("");
            writer.WriteLine($"public static {rowType}[] {methodName}()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"return new {rowType}[]");
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var row in rows)
                writer.WriteLine(createInitializer(row) + ",");

            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static string WriteAbilityInitializer(AbilityDefinitionRowModel row)
        {
            return
                "new AbilityDefinitionRow { " +
                $"AbilityCode = {row.AbilityCode}, " +
                $"Level = {row.Level}, " +
                $"TimelineId = {row.TimelineId}, " +
                $"PrimaryGameplayEffectCode = {row.PrimaryGameplayEffectCode}, " +
                $"SecondaryGameplayEffectCode = {row.SecondaryGameplayEffectCode}, " +
                $"ActivationOwnedTagCode = {row.ActivationOwnedTagCode}, " +
                $"ActivationRequiredAllTagCodes = {IntArrayLiteral(row.ActivationRequiredAllTagCodes)}, " +
                $"ActivationRequiredAnyTagCodes = {IntArrayLiteral(row.ActivationRequiredAnyTagCodes)}, " +
                $"ActivationRequiredNoneTagCodes = {IntArrayLiteral(row.ActivationRequiredNoneTagCodes)}, " +
                $"ActivationBlockedAllTagCodes = {IntArrayLiteral(row.ActivationBlockedAllTagCodes)}, " +
                $"ActivationBlockedAnyTagCodes = {IntArrayLiteral(row.ActivationBlockedAnyTagCodes)}, " +
                $"ActivationBlockedNoneTagCodes = {IntArrayLiteral(row.ActivationBlockedNoneTagCodes)}, " +
                $"CostGameplayEffectCode = {row.CostGameplayEffectCode}, " +
                $"CooldownGameplayEffectCode = {row.CooldownGameplayEffectCode}, " +
                $"CooldownFrames = {row.CooldownFrames}, " +
                $"TargetRuleCode = {row.TargetRuleCode} }}";
        }

        private static string WriteGameplayEffectInitializer(GameplayEffectDefinitionRowModel row)
        {
            return
                "new GameplayEffectDefinitionRow { " +
                $"GameplayEffectCode = {row.GameplayEffectCode}, " +
                $"Name = {StringLiteral(row.Name)}, " +
                $"ModifierAttributeSetCode = {row.ModifierAttributeSetCode}, " +
                $"ModifierAttributeCode = {row.ModifierAttributeCode}, " +
                $"ModifierOperation = {row.ModifierOperation}, " +
                $"ModifierMagnitude = {FloatLiteral(row.ModifierMagnitude)}, " +
                $"ModifierMagnitudeSource = {row.ModifierMagnitudeSource}, " +
                $"ModifierMagnitudeKey = {row.ModifierMagnitudeKey}, " +
                $"ModifierAttributeSetCodes = {IntArrayLiteral(row.ModifierAttributeSetCodes)}, " +
                $"ModifierAttributeCodes = {IntArrayLiteral(row.ModifierAttributeCodes)}, " +
                $"ModifierOperations = {IntArrayLiteral(row.ModifierOperations)}, " +
                $"ModifierMagnitudes = {FloatArrayLiteral(row.ModifierMagnitudes)}, " +
                $"ModifierMagnitudeSources = {IntArrayLiteral(row.ModifierMagnitudeSources)}, " +
                $"ModifierMagnitudeKeys = {IntArrayLiteral(row.ModifierMagnitudeKeys)}, " +
                $"DurationFrames = {row.DurationFrames}, " +
                $"PeriodFrames = {row.PeriodFrames}, " +
                $"PeriodGameplayEffectCode = {row.PeriodGameplayEffectCode}, " +
                $"GrantedTagCode = {row.GrantedTagCode}, " +
                $"GameplayCueCode = {row.GameplayCueCode}, " +
                $"DamageTypeCode = {row.DamageTypeCode}, " +
                $"ResistanceAttributeSetCode = {row.ResistanceAttributeSetCode}, " +
                $"ResistanceAttributeCode = {row.ResistanceAttributeCode}, " +
                $"ResistanceCap = {FloatLiteral(row.ResistanceCap)}, " +
                $"RemoveGameplayEffectTagCode = {row.RemoveGameplayEffectTagCode}, " +
                $"ApplicationRequiredAllTagCodes = {IntArrayLiteral(row.ApplicationRequiredAllTagCodes)}, " +
                $"ApplicationRequiredAnyTagCodes = {IntArrayLiteral(row.ApplicationRequiredAnyTagCodes)}, " +
                $"ApplicationRequiredNoneTagCodes = {IntArrayLiteral(row.ApplicationRequiredNoneTagCodes)}, " +
                $"OngoingRequiredAllTagCodes = {IntArrayLiteral(row.OngoingRequiredAllTagCodes)}, " +
                $"OngoingRequiredAnyTagCodes = {IntArrayLiteral(row.OngoingRequiredAnyTagCodes)}, " +
                $"OngoingRequiredNoneTagCodes = {IntArrayLiteral(row.OngoingRequiredNoneTagCodes)}, " +
                $"RemoveGameplayEffectAllTagCodes = {IntArrayLiteral(row.RemoveGameplayEffectAllTagCodes)}, " +
                $"RemoveGameplayEffectAnyTagCodes = {IntArrayLiteral(row.RemoveGameplayEffectAnyTagCodes)}, " +
                $"RemoveGameplayEffectNoneTagCodes = {IntArrayLiteral(row.RemoveGameplayEffectNoneTagCodes)}, " +
                $"ImmunityAllTagCodes = {IntArrayLiteral(row.ImmunityAllTagCodes)}, " +
                $"ImmunityAnyTagCodes = {IntArrayLiteral(row.ImmunityAnyTagCodes)}, " +
                $"ImmunityNoneTagCodes = {IntArrayLiteral(row.ImmunityNoneTagCodes)}, " +
                $"StackingCode = {row.StackingCode}, " +
                $"StackLimitCount = {row.StackLimitCount}, " +
                $"StackType = {row.StackType}, " +
                $"EffectDurationRefreshPolicy = {row.EffectDurationRefreshPolicy}, " +
                $"EffectPeriodResetPolicy = {row.EffectPeriodResetPolicy}, " +
                $"EffectExpirationPolicy = {row.EffectExpirationPolicy}, " +
                $"DenyOverflowApplication = {BoolLiteral(row.DenyOverflowApplication)}, " +
                $"ClearStackOnOverflow = {BoolLiteral(row.ClearStackOnOverflow)}, " +
                $"OverflowGameplayEffectCode = {row.OverflowGameplayEffectCode} }}";
        }

        private static string WriteAttributeSetInitializer(AttributeSetDefinitionRowModel row)
        {
            return $"new AttributeSetDefinitionRow {{ AttributeSetCode = {row.AttributeSetCode} }}";
        }

        private static string WriteAttributeInitializer(AttributeDefinitionRowModel row)
        {
            return
                "new AttributeDefinitionRow { " +
                $"AttributeSetCode = {row.AttributeSetCode}, " +
                $"AttributeCode = {row.AttributeCode}, " +
                $"InitialValue = {FloatLiteral(row.InitialValue)}, " +
                $"IsClampMin = {BoolLiteral(row.IsClampMin)}, " +
                $"IsClampMax = {BoolLiteral(row.IsClampMax)}, " +
                $"MinValue = {FloatLiteral(row.MinValue)}, " +
                $"MaxValue = {FloatLiteral(row.MaxValue)} }}";
        }

        private static string WriteGameplayTagInitializer(GameplayTagDefinitionRowModel row)
        {
            return
                "new GameplayTagDefinitionRow { " +
                $"GameplayTagCode = {row.GameplayTagCode}, " +
                $"ParentCodes = {IntArrayLiteral(row.ParentCodes)}, " +
                $"ChildCodes = {IntArrayLiteral(row.ChildCodes)} }}";
        }

        private static string WriteGameplayCueInitializer(GameplayCueDefinitionRowModel row)
        {
            return
                "new GameplayCueDefinitionRow { " +
                $"GameplayCueCode = {row.GameplayCueCode}, " +
                $"PresentationKey = {StringLiteral(row.PresentationKey)} }}";
        }

        private static string WriteTimelineInitializer(TimelineDefinitionRowModel row)
        {
            return
                "new TimelineDefinitionRow { " +
                $"TimelineId = {row.TimelineId}, " +
                $"GameplayEffectCode = {row.GameplayEffectCode}, " +
                $"SecondaryGameplayEffectCode = {row.SecondaryGameplayEffectCode}, " +
                $"TargetCatcherName = {StringLiteral(row.TargetCatcherName)} }}";
        }

        private static string ResolveProjectPath(string projectRoot, string path)
        {
            if (string.IsNullOrWhiteSpace(path))
                return projectRoot;

            return Path.GetFullPath(Path.IsPathRooted(path)
                ? path
                : Path.Combine(projectRoot, path));
        }

        private static void EnsureUnityMeta(string path)
        {
            var metaPath = path + ".meta";
            if (File.Exists(metaPath))
                return;

            File.WriteAllText(metaPath, "fileFormatVersion: 2\n" + $"guid: {CreateGuid()}\n");
        }

        private static string CreateGuid()
        {
            return Guid.NewGuid().ToString("N");
        }

        private static string IntArrayLiteral(IReadOnlyList<int> values)
        {
            return values == null || values.Count == 0
                ? "Array.Empty<int>()"
                : "new[] { " + string.Join(", ", values) + " }";
        }

        private static string FloatArrayLiteral(IReadOnlyList<float> values)
        {
            return values == null || values.Count == 0
                ? "Array.Empty<float>()"
                : "new[] { " + string.Join(", ", values.Select(FloatLiteral)) + " }";
        }

        private static string FloatLiteral(float value)
        {
            if (float.IsNaN(value))
                return "float.NaN";
            if (float.IsPositiveInfinity(value))
                return "float.PositiveInfinity";
            if (float.IsNegativeInfinity(value))
                return "float.NegativeInfinity";

            return value.ToString("R", CultureInfo.InvariantCulture) + "f";
        }

        private static string BoolLiteral(bool value)
        {
            return value ? "true" : "false";
        }

        private static string StringLiteral(string value)
        {
            if (value == null)
                return "string.Empty";

            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }

        private sealed class LubanNormalizedRowsModel
        {
            public IReadOnlyList<AbilityDefinitionRowModel> Abilities { get; private set; }
            public IReadOnlyList<GameplayEffectDefinitionRowModel> GameplayEffects { get; private set; }
            public IReadOnlyList<AttributeSetDefinitionRowModel> AttributeSets { get; private set; }
            public IReadOnlyList<AttributeDefinitionRowModel> Attributes { get; private set; }
            public IReadOnlyList<GameplayTagDefinitionRowModel> GameplayTags { get; private set; }
            public IReadOnlyList<GameplayCueDefinitionRowModel> GameplayCues { get; private set; }
            public IReadOnlyList<TimelineDefinitionRowModel> Timelines { get; private set; }

            public static LubanNormalizedRowsModel Create(string projectRoot, GasCodeGenSettings settings)
            {
                var reader = new LubanJsonReader(projectRoot, settings);
                var timelines = reader.CreateTimelineRows();
                return new LubanNormalizedRowsModel
                {
                    Timelines = timelines,
                    Abilities = reader.CreateAbilityRows(timelines),
                    GameplayEffects = reader.CreateGameplayEffectRows(),
                    AttributeSets = reader.CreateAttributeSetRows(),
                    Attributes = reader.CreateAttributeRows(),
                    GameplayTags = reader.CreateGameplayTagRows(),
                    GameplayCues = reader.CreateGameplayCueRows(),
                };
            }
        }

        private sealed class LubanJsonReader
        {
            private readonly string m_projectRoot;
            private readonly GasCodeGenSettings m_settings;

            public LubanJsonReader(string projectRoot, GasCodeGenSettings settings)
            {
                m_projectRoot = projectRoot;
                m_settings = settings;
            }

            public AbilityDefinitionRowModel[] CreateAbilityRows(IReadOnlyList<TimelineDefinitionRowModel> timelineRows)
            {
                var timelines = timelineRows.ToDictionary(row => row.TimelineId, row => row);
                return ReadArray(AbilityJson)
                    .Select(row => BuildAbilityRow(row, timelines))
                    .Where(row => row.AbilityCode > 0)
                    .OrderBy(row => row.AbilityCode)
                    .ToArray();
            }

            public GameplayEffectDefinitionRowModel[] CreateGameplayEffectRows()
            {
                return ReadArray(GameplayEffectJson)
                    .Select(BuildGameplayEffectRow)
                    .Where(row => row.GameplayEffectCode > 0)
                    .OrderBy(row => row.GameplayEffectCode)
                    .ToArray();
            }

            public AttributeSetDefinitionRowModel[] CreateAttributeSetRows()
            {
                return ReadArray(AttributeSetJson)
                    .Select(row => new AttributeSetDefinitionRowModel
                    {
                        AttributeSetCode = Int(row["ID"]),
                    })
                    .Where(row => row.AttributeSetCode > 0)
                    .OrderBy(row => row.AttributeSetCode)
                    .ToArray();
            }

            public AttributeDefinitionRowModel[] CreateAttributeRows()
            {
                var result = new List<AttributeDefinitionRowModel>();
                foreach (var attrSet in ReadArray(AttributeSetJson))
                {
                    var attrSetCode = Int(attrSet["ID"]);
                    if (attrSetCode <= 0)
                        continue;

                    foreach (var attribute in Array(attrSet["Attribute"]))
                    {
                        var attributeCode = Int(attribute["ID"]);
                        if (attributeCode <= 0)
                            continue;

                        result.Add(new AttributeDefinitionRowModel
                        {
                            AttributeSetCode = attrSetCode,
                            AttributeCode = attributeCode,
                            InitialValue = Float(attribute["InitValue"]),
                            IsClampMin = Bool(attribute["UseMinValue"]),
                            IsClampMax = Bool(attribute["UseMaxValue"]),
                            MinValue = Float(attribute["MinValue"]),
                            MaxValue = Float(attribute["MaxValue"]),
                        });
                    }
                }

                return result
                    .OrderBy(row => row.AttributeSetCode)
                    .ThenBy(row => row.AttributeCode)
                    .ToArray();
            }

            public GameplayTagDefinitionRowModel[] CreateGameplayTagRows()
            {
                var rows = ReadArray(GameplayTagJson)
                    .Select(row => new
                    {
                        Code = Int(row["id"]),
                        Name = String(row["Name"]),
                    })
                    .Where(row => row.Code > 0)
                    .ToArray();
                var codeByName = rows
                    .GroupBy(row => row.Name ?? string.Empty)
                    .ToDictionary(group => group.Key, group => group.First().Code);
                var childrenByCode = new Dictionary<int, List<int>>();
                var parentByCode = new Dictionary<int, List<int>>();

                foreach (var row in rows)
                {
                    var parentName = ParentTagName(row.Name);
                    if (string.IsNullOrEmpty(parentName) || !codeByName.TryGetValue(parentName, out var parentCode))
                        continue;

                    if (!childrenByCode.TryGetValue(parentCode, out var children))
                    {
                        children = new List<int>();
                        childrenByCode[parentCode] = children;
                    }

                    if (!parentByCode.TryGetValue(row.Code, out var parents))
                    {
                        parents = new List<int>();
                        parentByCode[row.Code] = parents;
                    }

                    children.Add(row.Code);
                    parents.Add(parentCode);
                }

                return rows
                    .OrderBy(row => row.Code)
                    .Select(row => new GameplayTagDefinitionRowModel
                    {
                        GameplayTagCode = row.Code,
                        ParentCodes = parentByCode.TryGetValue(row.Code, out var parents) ? parents.OrderBy(code => code).ToArray() : System.Array.Empty<int>(),
                        ChildCodes = childrenByCode.TryGetValue(row.Code, out var children) ? children.OrderBy(code => code).ToArray() : System.Array.Empty<int>(),
                    })
                    .ToArray();
            }

            public GameplayCueDefinitionRowModel[] CreateGameplayCueRows()
            {
                return ReadArray(GameplayCueJson)
                    .Select(row => new GameplayCueDefinitionRowModel
                    {
                        GameplayCueCode = Int(row["ID"]),
                        PresentationKey = String(row["Name"]),
                    })
                    .Where(row => row.GameplayCueCode > 0)
                    .OrderBy(row => row.GameplayCueCode)
                    .ToArray();
            }

            public TimelineDefinitionRowModel[] CreateTimelineRows()
            {
                return ReadArray(TimelineAbilityJson)
                    .Select(BuildTimelineRow)
                    .Where(row => row.TimelineId > 0)
                    .OrderBy(row => row.TimelineId)
                    .ToArray();
            }

            private AbilityDefinitionRowModel BuildAbilityRow(
                JToken row,
                IReadOnlyDictionary<int, TimelineDefinitionRowModel> timelines)
            {
                var abilityCode = Int(row["ID"]);
                var execution = row["AbilityExecution"];
                var timelineId = 0;
                var primaryGameplayEffectCode = 0;
                var secondaryGameplayEffectCode = 0;
                var targetRuleCode = 0;

                if (String(execution?["$type"]) == "TimelineRef")
                {
                    timelineId = Int(execution?["Param"]?["ID"]);
                    if (timelineId > 0 && timelines.TryGetValue(timelineId, out var timeline))
                    {
                        primaryGameplayEffectCode = timeline.GameplayEffectCode;
                        secondaryGameplayEffectCode = timeline.SecondaryGameplayEffectCode;
                        targetRuleCode = StableHash(timeline.TargetCatcherName);
                    }
                }
                else
                {
                    var ids = PositiveInts(execution?["Param"]?["IDs"]);
                    primaryGameplayEffectCode = ids.Length > 0 ? ids[0] : 0;
                    secondaryGameplayEffectCode = ids.Length > 1 ? ids[1] : 0;
                }

                var activationRequiredTags = ParseTagRequirement(row["ActivationRequiredTags"]);
                var activationBlockedTags = ParseTagRequirement(row["ActivationBlockedTags"]);

                return new AbilityDefinitionRowModel
                {
                    AbilityCode = abilityCode,
                    Level = 1,
                    TimelineId = timelineId,
                    PrimaryGameplayEffectCode = primaryGameplayEffectCode,
                    SecondaryGameplayEffectCode = secondaryGameplayEffectCode,
                    ActivationOwnedTagCode = FirstPositive(row["ActivationOwnedTags"]),
                    ActivationRequiredAllTagCodes = activationRequiredTags.All,
                    ActivationRequiredAnyTagCodes = activationRequiredTags.Any,
                    ActivationRequiredNoneTagCodes = activationRequiredTags.None,
                    ActivationBlockedAllTagCodes = activationBlockedTags.All,
                    ActivationBlockedAnyTagCodes = activationBlockedTags.Any,
                    ActivationBlockedNoneTagCodes = activationBlockedTags.None,
                    CostGameplayEffectCode = Int(row["Cost"]),
                    CooldownGameplayEffectCode = Int(row["CdEffect"]),
                    CooldownFrames = Int(row["Cd"]),
                    TargetRuleCode = targetRuleCode,
                };
            }

            private GameplayEffectDefinitionRowModel BuildGameplayEffectRow(JToken row)
            {
                var modifiers = Array(row["Modifiers"]);
                var normalizedModifiers = modifiers
                    .Select(BuildModifierRow)
                    .Where(modifier => modifier.AttributeSetCode > 0 && modifier.AttributeCode > 0)
                    .ToArray();
                var firstModifier = normalizedModifiers.Length > 0 ? normalizedModifiers[0] : default;
                var duration = row["Duration"];
                var period = row["Period"];
                var stacking = row["Stacking"];
                var applicationRequiredTags = ParseTagRequirement(row["ApplicationRequiredTags"]);
                var ongoingRequiredTags = ParseTagRequirement(row["OngoingRequiredTags"]);
                var removeGameplayEffectsWithTags = ParseTagRequirement(row["RemoveGameplayEffectsWithTags"]);
                var immunityTags = ParseTagRequirement(row["ImmunityTags"]);

                return new GameplayEffectDefinitionRowModel
                {
                    GameplayEffectCode = Int(row["ID"]),
                    Name = String(row["Name"]),
                    ModifierAttributeSetCode = firstModifier.AttributeSetCode,
                    ModifierAttributeCode = firstModifier.AttributeCode,
                    ModifierOperation = firstModifier.Operation,
                    ModifierMagnitude = firstModifier.Magnitude,
                    ModifierMagnitudeSource = 0,
                    ModifierMagnitudeKey = 0,
                    ModifierAttributeSetCodes = normalizedModifiers.Select(modifier => modifier.AttributeSetCode).ToArray(),
                    ModifierAttributeCodes = normalizedModifiers.Select(modifier => modifier.AttributeCode).ToArray(),
                    ModifierOperations = normalizedModifiers.Select(modifier => modifier.Operation).ToArray(),
                    ModifierMagnitudes = normalizedModifiers.Select(modifier => modifier.Magnitude).ToArray(),
                    ModifierMagnitudeSources = normalizedModifiers.Select(_ => 0).ToArray(),
                    ModifierMagnitudeKeys = normalizedModifiers.Select(_ => 0).ToArray(),
                    DurationFrames = Int(duration?["Time"]),
                    PeriodFrames = Int(period?["Time"]),
                    PeriodGameplayEffectCode = FirstPositive(period?["Effects"]),
                    GrantedTagCode = FirstPositive(row["GrantedTags"]),
                    GameplayCueCode = FirstPositive(row["CueOnApply"]),
                    DamageTypeCode = 0,
                    ResistanceAttributeSetCode = 0,
                    ResistanceAttributeCode = 0,
                    ResistanceCap = 0f,
                    RemoveGameplayEffectTagCode = FirstRequirementTag(row["RemoveGameplayEffectsWithTags"]),
                    ApplicationRequiredAllTagCodes = applicationRequiredTags.All,
                    ApplicationRequiredAnyTagCodes = applicationRequiredTags.Any,
                    ApplicationRequiredNoneTagCodes = applicationRequiredTags.None,
                    OngoingRequiredAllTagCodes = ongoingRequiredTags.All,
                    OngoingRequiredAnyTagCodes = ongoingRequiredTags.Any,
                    OngoingRequiredNoneTagCodes = ongoingRequiredTags.None,
                    RemoveGameplayEffectAllTagCodes = removeGameplayEffectsWithTags.All,
                    RemoveGameplayEffectAnyTagCodes = removeGameplayEffectsWithTags.Any,
                    RemoveGameplayEffectNoneTagCodes = removeGameplayEffectsWithTags.None,
                    ImmunityAllTagCodes = immunityTags.All,
                    ImmunityAnyTagCodes = immunityTags.Any,
                    ImmunityNoneTagCodes = immunityTags.None,
                    StackingCode = Int(stacking?["StackCode"]),
                    StackLimitCount = Int(stacking?["LimitCount"]),
                    StackType = Int(stacking?["StackingType"]),
                    EffectDurationRefreshPolicy = Int(stacking?["DurationRefreshPolicy"]),
                    EffectPeriodResetPolicy = Int(stacking?["PeriodResetPolicy"]),
                    EffectExpirationPolicy = Int(stacking?["ExpirationPolicy"]),
                    DenyOverflowApplication = Bool(stacking?["DenyOverflowApplication"]),
                    ClearStackOnOverflow = Bool(stacking?["ClearStackOnOverflow"]),
                    OverflowGameplayEffectCode = FirstPositive(stacking?["OverflowEffects"]),
                };
            }

            private ModifierRowModel BuildModifierRow(JToken row)
            {
                return new ModifierRowModel
                {
                    AttributeSetCode = Int(row?["AttrSet"]),
                    AttributeCode = Int(row?["Attribute"]),
                    Operation = Int(row?["Operation"]),
                    Magnitude = Float(row?["Magnitude"]),
                };
            }

            private TimelineDefinitionRowModel BuildTimelineRow(JToken row)
            {
                var effects = new List<int>();
                var targetCatcherName = string.Empty;
                foreach (var track in Array(row["Tracks"]))
                {
                    foreach (var clip in Array(track["ActionClips"]))
                    {
                        var action = clip["Action"];
                        if (String(action?["$type"]) != "ApplyEffects")
                            continue;

                        var param = action["Param"];
                        effects.AddRange(PositiveInts(param?["IDs"]));
                        if (string.IsNullOrEmpty(targetCatcherName))
                            targetCatcherName = String(param?["TargetCatcher"]?["$type"]);
                    }
                }

                return new TimelineDefinitionRowModel
                {
                    TimelineId = Int(row["ID"]),
                    GameplayEffectCode = effects.Count > 0 ? effects[0] : 0,
                    SecondaryGameplayEffectCode = effects.Count > 1 ? effects[1] : 0,
                    TargetCatcherName = targetCatcherName,
                };
            }

            private JArray ReadArray(string fileName)
            {
                var path = Path.Combine(m_projectRoot, m_settings.LubanDataOutputPath, fileName);
                if (!File.Exists(path))
                    throw new FileNotFoundException($"Luban JSON table is missing: {path}", path);

                var token = JToken.Parse(File.ReadAllText(path));
                if (token is JArray array)
                    return array;

                throw new InvalidDataException($"Luban JSON table root must be an array: {path}");
            }

            private static JArray Array(JToken token)
            {
                return token as JArray ?? new JArray();
            }

            private static int Int(JToken token)
            {
                return token == null || token.Type == JTokenType.Null ? 0 : token.Value<int>();
            }

            private static float Float(JToken token)
            {
                return token == null || token.Type == JTokenType.Null ? 0f : token.Value<float>();
            }

            private static bool Bool(JToken token)
            {
                return token != null && token.Type != JTokenType.Null && token.Value<bool>();
            }

            private static string String(JToken token)
            {
                return token == null || token.Type == JTokenType.Null ? string.Empty : token.Value<string>() ?? string.Empty;
            }

            private static int FirstPositive(JToken token)
            {
                var values = PositiveInts(token);
                return values.Length > 0 ? values[0] : 0;
            }

            private static TagRequirementRowModel ParseTagRequirement(JToken token)
            {
                if (token == null || token.Type == JTokenType.Null)
                    return TagRequirementRowModel.Empty;

                if (token is JArray)
                    return new TagRequirementRowModel(PositiveInts(token), System.Array.Empty<int>(), System.Array.Empty<int>());

                return new TagRequirementRowModel(
                    PositiveInts(token["All"]),
                    PositiveInts(token["Any"]),
                    PositiveInts(token["None"]));
            }

            private static int FirstRequirementTag(JToken token)
            {
                if (token == null || token.Type == JTokenType.Null)
                    return 0;

                var all = FirstPositive(token["All"]);
                if (all > 0)
                    return all;

                var any = FirstPositive(token["Any"]);
                return any > 0 ? any : 0;
            }

            private static int[] PositiveInts(JToken token)
            {
                if (token is not JArray array)
                    return System.Array.Empty<int>();

                return array
                    .Select(Int)
                    .Where(value => value > 0)
                    .ToArray();
            }

            private static string ParentTagName(string tagName)
            {
                if (string.IsNullOrWhiteSpace(tagName))
                    return string.Empty;

                var index = tagName.LastIndexOf('.');
                return index > 0 ? tagName.Substring(0, index) : string.Empty;
            }

            private static int StableHash(string value)
            {
                if (string.IsNullOrWhiteSpace(value))
                    return 0;

                unchecked
                {
                    var hash = (uint)2166136261;
                    for (var i = 0; i < value.Length; i++)
                    {
                        hash ^= value[i];
                        hash *= 16777619;
                    }

                    return (int)hash;
                }
            }
        }

        private sealed class AbilityDefinitionRowModel
        {
            public int AbilityCode;
            public int Level;
            public int TimelineId;
            public int PrimaryGameplayEffectCode;
            public int SecondaryGameplayEffectCode;
            public int ActivationOwnedTagCode;
            public int[] ActivationRequiredAllTagCodes;
            public int[] ActivationRequiredAnyTagCodes;
            public int[] ActivationRequiredNoneTagCodes;
            public int[] ActivationBlockedAllTagCodes;
            public int[] ActivationBlockedAnyTagCodes;
            public int[] ActivationBlockedNoneTagCodes;
            public int CostGameplayEffectCode;
            public int CooldownGameplayEffectCode;
            public int CooldownFrames;
            public int TargetRuleCode;
        }

        private sealed class GameplayEffectDefinitionRowModel
        {
            public int GameplayEffectCode;
            public string Name;
            public int ModifierAttributeSetCode;
            public int ModifierAttributeCode;
            public int ModifierOperation;
            public float ModifierMagnitude;
            public int ModifierMagnitudeSource;
            public int ModifierMagnitudeKey;
            public int[] ModifierAttributeSetCodes;
            public int[] ModifierAttributeCodes;
            public int[] ModifierOperations;
            public float[] ModifierMagnitudes;
            public int[] ModifierMagnitudeSources;
            public int[] ModifierMagnitudeKeys;
            public int DurationFrames;
            public int PeriodFrames;
            public int PeriodGameplayEffectCode;
            public int GrantedTagCode;
            public int GameplayCueCode;
            public int DamageTypeCode;
            public int ResistanceAttributeSetCode;
            public int ResistanceAttributeCode;
            public float ResistanceCap;
            public int RemoveGameplayEffectTagCode;
            public int[] ApplicationRequiredAllTagCodes;
            public int[] ApplicationRequiredAnyTagCodes;
            public int[] ApplicationRequiredNoneTagCodes;
            public int[] OngoingRequiredAllTagCodes;
            public int[] OngoingRequiredAnyTagCodes;
            public int[] OngoingRequiredNoneTagCodes;
            public int[] RemoveGameplayEffectAllTagCodes;
            public int[] RemoveGameplayEffectAnyTagCodes;
            public int[] RemoveGameplayEffectNoneTagCodes;
            public int[] ImmunityAllTagCodes;
            public int[] ImmunityAnyTagCodes;
            public int[] ImmunityNoneTagCodes;
            public int StackingCode;
            public int StackLimitCount;
            public int StackType;
            public int EffectDurationRefreshPolicy;
            public int EffectPeriodResetPolicy;
            public int EffectExpirationPolicy;
            public bool DenyOverflowApplication;
            public bool ClearStackOnOverflow;
            public int OverflowGameplayEffectCode;
        }

        private readonly struct TagRequirementRowModel
        {
            public readonly int[] All;
            public readonly int[] Any;
            public readonly int[] None;

            public TagRequirementRowModel(int[] all, int[] any, int[] none)
            {
                All = all ?? System.Array.Empty<int>();
                Any = any ?? System.Array.Empty<int>();
                None = none ?? System.Array.Empty<int>();
            }

            public static TagRequirementRowModel Empty => new(
                System.Array.Empty<int>(),
                System.Array.Empty<int>(),
                System.Array.Empty<int>());
        }

        private sealed class AttributeSetDefinitionRowModel
        {
            public int AttributeSetCode;
        }

        private sealed class AttributeDefinitionRowModel
        {
            public int AttributeSetCode;
            public int AttributeCode;
            public float InitialValue;
            public bool IsClampMin;
            public bool IsClampMax;
            public float MinValue;
            public float MaxValue;
        }

        private sealed class GameplayTagDefinitionRowModel
        {
            public int GameplayTagCode;
            public int[] ParentCodes;
            public int[] ChildCodes;
        }

        private sealed class GameplayCueDefinitionRowModel
        {
            public int GameplayCueCode;
            public string PresentationKey;
        }

        private sealed class TimelineDefinitionRowModel
        {
            public int TimelineId;
            public int GameplayEffectCode;
            public int SecondaryGameplayEffectCode;
            public string TargetCatcherName;
        }

        private struct ModifierRowModel
        {
            public int AttributeSetCode;
            public int AttributeCode;
            public int Operation;
            public float Magnitude;
        }
    }
}
