using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace GAS.Editor
{
    internal sealed class AutoChessDemoConfigPhase : GasCodeGenPhaseBase
    {
        public override string PhaseName => "AutoChessDemoConfig";

        public override IReadOnlyList<string> OutputFileNames { get; } =
            new[] { "../../../AutoChessDemo/Generated/AutoChessGeneratedConfig.gen.cs" };

        public override bool RequiresRows => false;

        public override void Execute(GasCodeGenContext context, GasCodeGenManifest manifest)
        {
            var path = GetOutputPath(context, OutputFileNames[0]);
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            AddRuntimeManifest(manifest, PhaseName, path);
            var model = AutoChessDemoConfigModel.FromLubanJson(context);

            using var stream = new StreamWriter(path);
            using var writer = new IndentedWriter(stream);
            WriteAutoChessHeader(writer);
            writer.WriteLine("namespace GAS.AutoChessDemo");
            writer.WriteLine("{");
            writer.Indent++;
            WriteScenarioProfile(writer);
            writer.WriteLine();
            WriteGeneratedUnitRow(writer);
            writer.WriteLine();
            WriteGeneratedConfig(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
            EnsureUnityMeta(path);
        }

        private static void WriteAutoChessHeader(IndentedWriter writer)
        {
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System;");
            writer.WriteLine();
        }

        private static void WriteScenarioProfile(IndentedWriter writer)
        {
            writer.WriteLine("public readonly struct AutoChessGeneratedScenarioProfile");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public readonly int Scale;");
            writer.WriteLine("public readonly int MaxTicks;");
            writer.WriteLine("public readonly int PostVictoryFlushTicks;");
            writer.WriteLine("public readonly int ProcessWarmupRuns;");
            writer.WriteLine("public readonly float HealthMultiplier;");
            writer.WriteLine("public readonly AutoChessTeam ExpectedWinner;");
            writer.WriteLine("public readonly int MinDriverIssuedCommands;");
            writer.WriteLine("public readonly int MinAttributeChanges;");
            writer.WriteLine("public readonly int MinExecutionOutputs;");
            writer.WriteLine("public readonly int MinCueRequests;");
            writer.WriteLine();
            writer.WriteLine("public AutoChessGeneratedScenarioProfile(");
            writer.Indent++;
            writer.WriteLine("int scale,");
            writer.WriteLine("int maxTicks,");
            writer.WriteLine("int postVictoryFlushTicks,");
            writer.WriteLine("int processWarmupRuns,");
            writer.WriteLine("float healthMultiplier,");
            writer.WriteLine("AutoChessTeam expectedWinner,");
            writer.WriteLine("int minDriverIssuedCommands,");
            writer.WriteLine("int minAttributeChanges,");
            writer.WriteLine("int minExecutionOutputs,");
            writer.WriteLine("int minCueRequests)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Scale = scale;");
            writer.WriteLine("MaxTicks = maxTicks;");
            writer.WriteLine("PostVictoryFlushTicks = postVictoryFlushTicks;");
            writer.WriteLine("ProcessWarmupRuns = processWarmupRuns;");
            writer.WriteLine("HealthMultiplier = healthMultiplier;");
            writer.WriteLine("ExpectedWinner = expectedWinner;");
            writer.WriteLine("MinDriverIssuedCommands = minDriverIssuedCommands;");
            writer.WriteLine("MinAttributeChanges = minAttributeChanges;");
            writer.WriteLine("MinExecutionOutputs = minExecutionOutputs;");
            writer.WriteLine("MinCueRequests = minCueRequests;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteGeneratedUnitRow(IndentedWriter writer)
        {
            writer.WriteLine("public readonly struct AutoChessGeneratedUnitRow");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public readonly string Id;");
            writer.WriteLine("public readonly string DisplayName;");
            writer.WriteLine("public readonly string ArchetypeName;");
            writer.WriteLine("public readonly AutoChessTeam Team;");
            writer.WriteLine("public readonly int Slot;");
            writer.WriteLine("public readonly float Health;");
            writer.WriteLine("public readonly float Energy;");
            writer.WriteLine("public readonly int PrimaryAbilityCode;");
            writer.WriteLine("public readonly int FinisherAbilityCode;");
            writer.WriteLine("public readonly float FinisherHealthThreshold;");
            writer.WriteLine("public readonly AutoChessTargetPolicy PrimaryTargetPolicy;");
            writer.WriteLine("public readonly AutoChessTargetPolicy FinisherTargetPolicy;");
            writer.WriteLine();
            writer.WriteLine("public AutoChessGeneratedUnitRow(");
            writer.Indent++;
            writer.WriteLine("string id,");
            writer.WriteLine("string displayName,");
            writer.WriteLine("string archetypeName,");
            writer.WriteLine("AutoChessTeam team,");
            writer.WriteLine("int slot,");
            writer.WriteLine("float health,");
            writer.WriteLine("float energy,");
            writer.WriteLine("int primaryAbilityCode,");
            writer.WriteLine("int finisherAbilityCode,");
            writer.WriteLine("float finisherHealthThreshold,");
            writer.WriteLine("AutoChessTargetPolicy primaryTargetPolicy,");
            writer.WriteLine("AutoChessTargetPolicy finisherTargetPolicy)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Id = id ?? string.Empty;");
            writer.WriteLine("DisplayName = displayName ?? string.Empty;");
            writer.WriteLine("ArchetypeName = archetypeName ?? string.Empty;");
            writer.WriteLine("Team = team;");
            writer.WriteLine("Slot = slot;");
            writer.WriteLine("Health = health;");
            writer.WriteLine("Energy = energy;");
            writer.WriteLine("PrimaryAbilityCode = primaryAbilityCode;");
            writer.WriteLine("FinisherAbilityCode = finisherAbilityCode;");
            writer.WriteLine("FinisherHealthThreshold = finisherHealthThreshold;");
            writer.WriteLine("PrimaryTargetPolicy = primaryTargetPolicy;");
            writer.WriteLine("FinisherTargetPolicy = finisherTargetPolicy;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteGeneratedConfig(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine("public static class AutoChessGeneratedConfig");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public const string RoomIdPrefix = \"room-standard-duel-x\";");
            writer.WriteLine("public const string RoomDisplayName = \"标准双人自走棋对局\";");
            writer.WriteLine("public const string PlayerId = \"player-a\";");
            writer.WriteLine("public const string EnemyId = \"player-b\";");
            writer.WriteLine("public const string PlayerDisplayName = \"玩家A\";");
            writer.WriteLine("public const string EnemyDisplayName = \"玩家B\";");
            writer.WriteLine();
            writer.WriteLine($"public const int AttributeSetCombat = {model.AttributeSetCombat};");
            writer.WriteLine($"public const int AttributeHealth = {model.AttributeHealth};");
            writer.WriteLine($"public const int AttributeEnergy = {model.AttributeEnergy};");
            writer.WriteLine($"public const int AbilityPlayerAttack = {model.AbilityPlayerAttack};");
            writer.WriteLine($"public const int AbilityEnemyAttack = {model.AbilityEnemyAttack};");
            writer.WriteLine($"public const int AbilityPlayerExecute = {model.AbilityPlayerExecute};");
            writer.WriteLine($"public const int GameplayEffectPlayerAttackDamage = {model.GameplayEffectPlayerAttackDamage};");
            writer.WriteLine($"public const int GameplayEffectEnemyAttackDamage = {model.GameplayEffectEnemyAttackDamage};");
            writer.WriteLine($"public const int GameplayEffectPlayerExecute = {model.GameplayEffectPlayerExecute};");
            writer.WriteLine($"public const int ExecutionCalculationExecuteDamage = {model.ExecutionCalculationExecuteDamage};");
            writer.WriteLine($"public const int ExecutionCalculationExecuteDamageOutput = {model.ExecutionCalculationExecuteDamageOutput};");
            writer.WriteLine($"public const int TagAttackCooldown = {model.TagAttackCooldown};");
            writer.WriteLine();
            writer.WriteLine("public static AutoChessGeneratedScenarioProfile ValidationScenario => new AutoChessGeneratedScenarioProfile(");
            writer.Indent++;
            writer.WriteLine($"{model.ValidationScenario.Scale},");
            writer.WriteLine($"{model.ValidationScenario.MaxTicks},");
            writer.WriteLine($"{model.ValidationScenario.PostVictoryFlushTicks},");
            writer.WriteLine($"{model.ValidationScenario.ProcessWarmupRuns},");
            writer.WriteLine($"{FloatLiteral(model.ValidationScenario.HealthMultiplier)},");
            writer.WriteLine($"{model.ValidationScenario.ExpectedWinner},");
            writer.WriteLine($"{model.ValidationScenario.MinDriverIssuedCommands},");
            writer.WriteLine($"{model.ValidationScenario.MinAttributeChanges},");
            writer.WriteLine($"{model.ValidationScenario.MinExecutionOutputs},");
            writer.WriteLine($"{model.ValidationScenario.MinCueRequests});");
            writer.Indent--;
            writer.WriteLine();
            WriteCreateBaseUnitRows(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteCreateBaseUnitRows(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine("public static AutoChessGeneratedUnitRow[] CreateBaseUnitRows()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new[]");
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var unit in model.BaseUnits)
                WriteUnit(writer, unit);
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteUnit(IndentedWriter writer, AutoChessDemoUnitModel unit)
        {
            writer.WriteLine("new AutoChessGeneratedUnitRow(");
            writer.Indent++;
            writer.WriteLine($"{StringLiteral(unit.Id)},");
            writer.WriteLine($"{StringLiteral(unit.DisplayName)},");
            writer.WriteLine($"{StringLiteral(unit.ArchetypeName)},");
            writer.WriteLine($"{unit.Team},");
            writer.WriteLine($"{unit.Slot.ToString(CultureInfo.InvariantCulture)},");
            writer.WriteLine($"{FloatLiteral(unit.Health)},");
            writer.WriteLine($"{FloatLiteral(unit.Energy)},");
            writer.WriteLine($"{unit.PrimaryAbilityCode},");
            writer.WriteLine($"{unit.FinisherAbilityCode},");
            writer.WriteLine($"{FloatLiteral(unit.FinisherHealthThreshold)},");
            writer.WriteLine($"{unit.PrimaryTargetPolicy},");
            writer.WriteLine($"{unit.FinisherTargetPolicy}),");
            writer.Indent--;
        }

        private static string FloatLiteral(float value)
        {
            return value.ToString("0.########", CultureInfo.InvariantCulture) + "f";
        }

        private static string StringLiteral(string value)
        {
            if (value == null)
                return "string.Empty";

            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }

        private static void EnsureUnityMeta(string path)
        {
            var metaPath = path + ".meta";
            if (File.Exists(metaPath))
                return;

            File.WriteAllText(
                metaPath,
                "fileFormatVersion: 2\n"
                + "guid: " + CreateGuid(path) + "\n"
                + "MonoImporter:\n"
                + "  externalObjects: {}\n"
                + "  serializedVersion: 2\n"
                + "  defaultReferences: []\n"
                + "  executionOrder: 0\n"
                + "  icon: {instanceID: 0}\n"
                + "  userData: \n"
                + "  assetBundleName: \n"
                + "  assetBundleVariant: \n");
        }

        private static string CreateGuid(string path)
        {
            unchecked
            {
                var hash = 17;
                for (var i = 0; i < path.Length; i++)
                    hash = hash * 31 + char.ToLowerInvariant(path[i]);

                var value = Math.Abs(hash).ToString("x8", CultureInfo.InvariantCulture);
                return value + value + value + value;
            }
        }
    }
}
