using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;

namespace GAS.Editor
{
    /// <summary>
    /// 从 Luban 权威 JSON 生成 AutoChess 场景 glue 与 Runtime v1 immutable Catalog pure data。
    /// </summary>
    internal sealed class AutoChessDemoConfigPhase : GasCodeGenPhaseBase
    {
        public override string PhaseName => "AutoChessDemoConfig";

        public override IReadOnlyList<string> OutputFileNames { get; } =
            new[] { "AutoChessGeneratedConfig.gen.cs" };

        public override bool RequiresRows => false;

        /// <summary>
        /// 生成单一 AutoChess artifact；遇到不可无损映射的 Luban 语义时由模型阶段 fail-fast。
        /// </summary>
        public override void Execute(GasCodeGenContext context, GasCodeGenManifest manifest)
        {
            var path = GetOutputPath(context, OutputFileNames[0]);
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            AddRuntimeManifest(manifest, PhaseName, path);
            var model = AutoChessDemoConfigModel.FromLubanJson(context);
            var catalogPlan = CatalogEmissionPlan.Create(model.RuntimeCatalog);

            using var stream = new StreamWriter(path);
            using var writer = new IndentedWriter(stream);
            WriteAutoChessHeader(writer);
            writer.WriteLine("namespace GAS.AutoChessDemo");
            writer.WriteLine("{");
            writer.Indent++;
            WriteScenarioProfile(writer);
            writer.WriteLine();
            WriteGeneratedUnitSpawnPlan(writer);
            writer.WriteLine();
            WriteGeneratedDefinitionCatalog(writer, catalogPlan);
            writer.WriteLine();
            WriteGeneratedConfig(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
            EnsureUnityMeta(path);
        }

        /// <summary>
        /// 写入 generated artifact 所需的最小 using 集合。
        /// </summary>
        private static void WriteAutoChessHeader(IndentedWriter writer)
        {
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System;");
            writer.WriteLine("using GAS.Runtime;");
            writer.WriteLine("using Unity.Collections;");
            writer.WriteLine("using Unity.Entities;");
            writer.WriteLine();
        }

        /// <summary>
        /// 写入独立验证场景的只读 generated value object。
        /// </summary>
        private static void WriteScenarioProfile(IndentedWriter writer)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 保存 generated AutoChess 验证场景阈值。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public readonly struct AutoChessGeneratedScenarioProfile");
            writer.WriteLine("{");
            writer.Indent++;
            var fields = new[]
            {
                "int Scale", "int MaxTicks", "float HealthMultiplier", "AutoChessTeam ExpectedWinner",
                "int MinAcceptedCommands", "int MinAttributeChanges", "int MinExecutionOutputs",
                "int MinCueRequests", "int MinActiveEffectSlots", "int MinPeriodTickDamageFacts",
                "int MinActiveMutationCommands", "int MinActiveMutationOwnerGroups",
                "int MaxActiveMutationEstimatedRandomLookups", "int MaxActiveMutationOwnerResourceLookups",
                "int MaxActiveMutationMigrationCarriers",
            };
            foreach (var field in fields)
                writer.WriteLine($"public readonly {field};");
            writer.WriteLine();
            WriteScenarioConstructor(writer, fields);
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入场景 profile 构造函数及逐字段赋值。
        /// </summary>
        private static void WriteScenarioConstructor(IndentedWriter writer, IReadOnlyList<string> fields)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建一个 generated 验证场景 profile。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public AutoChessGeneratedScenarioProfile(");
            writer.Indent++;
            for (var index = 0; index < fields.Count; index++)
            {
                var parts = fields[index].Split(' ');
                var parameterName = char.ToLowerInvariant(parts[1][0]) + parts[1].Substring(1);
                writer.WriteLine($"{parts[0]} {parameterName}{(index + 1 < fields.Count ? "," : ")")}");
            }
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var field in fields)
            {
                var name = field.Split(' ')[1];
                var parameterName = char.ToLowerInvariant(name[0]) + name.Substring(1);
                writer.WriteLine($"{name} = {parameterName};");
            }
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入场景单位的 generated spawn plan 类型。
        /// </summary>
        private static void WriteGeneratedUnitSpawnPlan(IndentedWriter writer)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 保存 generated AutoChess 单位生成参数。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public readonly struct AutoChessGeneratedUnitSpawnPlan");
            writer.WriteLine("{");
            writer.Indent++;
            var fields = UnitFields();
            foreach (var field in fields)
                writer.WriteLine($"public readonly {field};");
            writer.WriteLine();
            WriteUnitConstructor(writer, fields);
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 返回单位 spawn plan 的稳定字段列表。
        /// </summary>
        private static string[] UnitFields()
        {
            return new[]
            {
                "string Id", "string DisplayName", "string ArchetypeName", "AutoChessTeam Team",
                "int Slot", "float Health", "float Energy", "float Attack", "int PrimaryAbilityCode",
                "int FinisherAbilityCode", "int ActiveAbilityCode", "int ActiveCastInterval",
                "int ActiveCastFrameOffset", "float FinisherHealthThreshold",
                "AutoChessTargetPolicy PrimaryTargetPolicy", "AutoChessTargetPolicy FinisherTargetPolicy",
            };
        }

        /// <summary>
        /// 写入单位 spawn plan 构造函数。
        /// </summary>
        private static void WriteUnitConstructor(IndentedWriter writer, IReadOnlyList<string> fields)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建一个 generated 单位 spawn plan。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public AutoChessGeneratedUnitSpawnPlan(");
            writer.Indent++;
            for (var index = 0; index < fields.Count; index++)
            {
                var parts = fields[index].Split(' ');
                var name = char.ToLowerInvariant(parts[1][0]) + parts[1].Substring(1);
                writer.WriteLine($"{parts[0]} {name}{(index + 1 < fields.Count ? "," : ")")}");
            }
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var field in fields)
            {
                var name = field.Split(' ')[1];
                var parameterName = char.ToLowerInvariant(name[0]) + name.Substring(1);
                writer.WriteLine($"{name} = {parameterName}{(field.StartsWith("string ", StringComparison.Ordinal) ? " ?? string.Empty" : string.Empty)};");
            }
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入 generated Catalog 入口与全部 pure-data 数组工厂。
        /// </summary>
        private static void WriteGeneratedDefinitionCatalog(
            IndentedWriter writer,
            CatalogEmissionPlan plan)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 由 Luban 权威表生成 AutoChess Runtime v1 Catalog pure data。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("internal static class AutoChessGeneratedDefinitionCatalog");
            writer.WriteLine("{");
            writer.Indent++;
            WriteCatalogBuildEntry(writer);
            writer.WriteLine();
            WriteCatalogSourceFactory(writer);
            writer.WriteLine();
            WriteAttributeFactory(writer, plan);
            writer.WriteLine();
            WriteIndexFactories(writer, plan);
            writer.WriteLine();
            WriteAbilityFactories(writer, plan);
            writer.WriteLine();
            WriteEffectFactories(writer, plan);
            writer.WriteLine();
            WritePayloadFactories(writer, plan);
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入 generated Catalog 的唯一构建入口。
        /// </summary>
        private static void WriteCatalogBuildEntry(IndentedWriter writer)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 两遍物化 generated source，并返回独立冻结的 Stage-B 期望身份。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("internal static BlobAssetReference<GasDefinitionCatalogBlob> Build(");
            writer.Indent++;
            writer.WriteLine("Allocator allocator,");
            writer.WriteLine("out GasCatalogValidationExpectation expectation)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return AutoChessDefinitionCatalogCompiler.Build(CreateSource(), allocator, out expectation);");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入聚合全部 generated 数组的 source object 工厂。
        /// </summary>
        private static void WriteCatalogSourceFactory(IndentedWriter writer)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建不含手写玩法常量的 generated Catalog source。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("private static AutoChessDefinitionCatalogSource CreateSource()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new AutoChessDefinitionCatalogSource");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Attributes = CreateAttributes(),");
            writer.WriteLine("AbilityIndex = CreateAbilityIndex(),");
            writer.WriteLine("Abilities = CreateAbilities(),");
            writer.WriteLine("GameplayEffectIndex = CreateGameplayEffectIndex(),");
            writer.WriteLine("GameplayEffects = CreateGameplayEffects(),");
            writer.WriteLine("CaptureDescriptors = CreateCaptureDescriptors(),");
            writer.WriteLine("Modifiers = CreateModifiers(),");
            writer.WriteLine("DirectEffectProgramNodes = CreateDirectEffectProgramNodes(),");
            writer.WriteLine("CueReferences = CreateCueReferences(),");
            writer.WriteLine("ValueViews = CreateValueViews(),");
            writer.WriteLine("EvaluatorInstructions = CreateEvaluatorInstructions(),");
            writer.WriteLine("TargetDataDescriptors = CreateTargetDataDescriptors(),");
            writer.WriteLine("EffectContextFieldDescriptors = CreateEffectContextFieldDescriptors(),");
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入 dense Attribute layout 数组。
        /// </summary>
        private static void WriteAttributeFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建按 Attribute ID 排序的 dense layout。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("private static GasAttributeLayoutEntryBlob[] CreateAttributes()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new[]");
            writer.WriteLine("{");
            writer.Indent++;
            for (var index = 0; index < plan.Model.Attributes.Length; index++)
                WriteAttribute(writer, plan.Model.Attributes[index], index);
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入一个 Attribute layout 条目。
        /// </summary>
        private static void WriteAttribute(
            IndentedWriter writer,
            in AutoChessAttributeRow row,
            int layoutIndex)
        {
            writer.WriteLine("new GasAttributeLayoutEntryBlob");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"AttributeId = {row.AttributeCode},");
            writer.WriteLine($"LayoutIndex = {layoutIndex},");
            writer.WriteLine($"DomainRole = (GasAttributeDomainRole){row.DomainRole},");
            writer.WriteLine($"DefaultValue = {FloatLiteral(row.InitialValue)},");
            writer.WriteLine($"MinimumValue = {FloatLiteral(row.MinimumValue)},");
            writer.WriteLine($"MaximumValue = {FloatLiteral(row.MaximumValue)},");
            writer.WriteLine($"ClampMinimum = {(row.ClampMinimum ? 1 : 0)},");
            writer.WriteLine($"ClampMaximum = {(row.ClampMaximum ? 1 : 0)},");
            writer.Indent--;
            writer.WriteLine("},");
        }

        /// <summary>
        /// 写入 Ability 与 GameplayEffect 的稳定索引数组。
        /// </summary>
        private static void WriteIndexFactories(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteIndexFactory(
                writer,
                "CreateAbilityIndex",
                plan.Model.Abilities.Select(row => row.AbilityCode).ToArray());
            writer.WriteLine();
            WriteIndexFactory(
                writer,
                "CreateGameplayEffectIndex",
                plan.Effects.Select(effect => effect.Row.GameplayEffectCode).ToArray());
        }

        /// <summary>
        /// 写入一个 Definition ID 到数组索引的 generated 工厂。
        /// </summary>
        private static void WriteIndexFactory(
            IndentedWriter writer,
            string methodName,
            IReadOnlyList<int> definitionIds)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建稳定 Definition 索引。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine($"private static GasDefinitionIndexEntry[] {methodName}()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new[]");
            writer.WriteLine("{");
            writer.Indent++;
            for (var index = 0; index < definitionIds.Count; index++)
                writer.WriteLine($"new GasDefinitionIndexEntry {{ DefinitionId = {definitionIds[index]}, DefinitionIndex = {index} }},");
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入 Ability 数组与每个 Ability definition 工厂。
        /// </summary>
        private static void WriteAbilityFactories(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建全部 Ability definitions。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("private static GasAbilityDefinitionBlob[] CreateAbilities()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new[]");
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var ability in plan.Model.Abilities)
                writer.WriteLine($"CreateAbility{ability.AbilityCode}(),");
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
            for (var index = 0; index < plan.Model.Abilities.Length; index++)
            {
                writer.WriteLine();
                WriteAbilityFactory(writer, plan.Model.Abilities[index], index);
            }
        }

        /// <summary>
        /// 写入一个 Ability definition 工厂。
        /// </summary>
        private static void WriteAbilityFactory(
            IndentedWriter writer,
            in AutoChessAbilityRow ability,
            int directNodeIndex)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// 创建 Luban Ability {ability.AbilityCode} 的 Runtime v1 definition。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine($"private static GasAbilityDefinitionBlob CreateAbility{ability.AbilityCode}()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new GasAbilityDefinitionBlob");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"DefinitionId = {ability.AbilityCode},");
            writer.WriteLine("Level = 1,");
            writer.WriteLine("MaxConcurrentActivations = 1,");
            WriteTargetPolicy(writer, in ability.TargetPolicy);
            writer.WriteLine($"DirectEffectProgramRange = Range({directNodeIndex}, 1),");
            WriteMaxima(writer, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1);
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入 GameplayEffect 数组与逐 definition 工厂。
        /// </summary>
        private static void WriteEffectFactories(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建 root 与 period child 的完整 GameplayEffect 闭包。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("private static GasGameplayEffectDefinitionBlob[] CreateGameplayEffects()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new[]");
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var effect in plan.Effects)
                writer.WriteLine($"CreateEffect{effect.Row.GameplayEffectCode}(),");
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
            foreach (var effect in plan.Effects)
            {
                writer.WriteLine();
                WriteEffectFactory(writer, effect);
            }
            writer.WriteLine();
            WriteRangeFactory(writer);
        }

        /// <summary>
        /// 写入一个 GameplayEffect definition 及其精确 ranges/maxima。
        /// </summary>
        private static void WriteEffectFactory(IndentedWriter writer, EffectEmissionPlan effect)
        {
            var row = effect.Row;
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// 创建 Luban GameplayEffect {row.GameplayEffectCode} 的 Runtime v1 definition。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine($"private static GasGameplayEffectDefinitionBlob CreateEffect{row.GameplayEffectCode}()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new GasGameplayEffectDefinitionBlob");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"DefinitionId = {row.GameplayEffectCode},");
            writer.WriteLine($"Lifetime = GasEffectLifetimePolicy.{effect.Lifetime},");
            WriteTargetPolicy(writer, in row.TargetPolicy);
            writer.WriteLine($"CaptureRange = Range({effect.CaptureStart}, {effect.CaptureCount}),");
            writer.WriteLine($"ModifierRange = Range({effect.ModifierStart}, {effect.ModifierCount}),");
            writer.WriteLine($"CueRange = Range({effect.CueStart}, {effect.CueCount}),");
            writer.WriteLine($"ValueViewRange = Range({effect.ValueViewStart}, {effect.ValueViewCount}),");
            writer.WriteLine($"EvaluatorProgramRange = Range({effect.EvaluatorStart}, {effect.EvaluatorCount}),");
            writer.WriteLine($"TargetDataRange = Range({effect.TargetDataStart}, 1),");
            writer.WriteLine($"EffectContextFieldRange = Range({effect.ContextStart}, 3),");
            writer.WriteLine($"RequiredValueViews = {effect.RequiredValueViews},");
            WriteEffectPolicies(writer, effect);
            WriteMaxima(
                writer,
                effect.ModifierCount,
                effect.CueCount,
                0,
                effect.ValueViewCount,
                effect.EvaluatorCount,
                1,
                3,
                effect.CaptureCount,
                1,
                1);
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入 GameplayEffect 的 duration、period、stack 与 inhibition 策略。
        /// </summary>
        private static void WriteEffectPolicies(IndentedWriter writer, EffectEmissionPlan effect)
        {
            var row = effect.Row;
            var stacking = row.Stacking;
            writer.WriteLine($"DurationTicks = {(row.Duration.IsDefined ? row.Duration.Time : 0)},");
            writer.WriteLine($"PeriodTicks = {(row.Period.IsDefined ? row.Period.Time : 0)},");
            writer.WriteLine($"StackLimit = {(stacking.IsDefined ? stacking.LimitCount : 0)},");
            writer.WriteLine($"StackKey = {(stacking.IsDefined ? "GasStackKeyFields.Definition | GasStackKeyFields.TargetAsc | GasStackKeyFields.SourceAsc" : "GasStackKeyFields.None")},");
            writer.WriteLine($"StackPolicy = {(stacking.IsDefined ? (stacking.StackingType == 0 ? "GasStackPolicy.AggregateBySource" : "GasStackPolicy.AggregateByTarget") : "GasStackPolicy.None")},");
            writer.WriteLine($"StackPayloadPolicy = {(stacking.IsDefined ? "GasStackPayloadPolicy.ReplaceLatestPayloadAndProvenance" : "GasStackPayloadPolicy.None")},");
            writer.WriteLine($"StackLimitApplicationPolicy = {(stacking.IsDefined && stacking.DenyOverflowApplication ? "GasStackLimitApplicationPolicy.RejectAtLimit" : stacking.IsDefined ? "GasStackLimitApplicationPolicy.AcceptAndKeepLimit" : "GasStackLimitApplicationPolicy.None")},");
            writer.WriteLine($"DurationRefreshPolicy = {(stacking.IsDefined && stacking.DurationRefreshPolicy == 1 ? "GasDurationRefreshPolicy.OnSuccessfulApplication" : "GasDurationRefreshPolicy.Never")},");
            writer.WriteLine($"PeriodResetPolicy = {(stacking.IsDefined && stacking.PeriodResetPolicy == 1 ? "GasPeriodResetPolicy.OnSuccessfulApplication" : "GasPeriodResetPolicy.Never")},");
            writer.WriteLine($"ExpiryPolicy = {(stacking.IsDefined && stacking.ExpirationPolicy == 1 ? "GasExpiryPolicy.RemoveOneStackAndRefreshDuration" : "GasExpiryPolicy.Remove")},");
            writer.WriteLine($"ExpiryPeriodPolicy = {(stacking.IsDefined && stacking.ExpirationPolicy == 1 ? "GasExpiryPeriodPolicy.Reset" : "GasExpiryPeriodPolicy.Stop")},");
            writer.WriteLine($"ExpirySameTickPolicy = {(row.Period.IsDefined ? "GasExpirySameTickPolicy.PeriodDueBeforeExpiry" : "GasExpirySameTickPolicy.ExpiryBeforePeriodDue")},");
            writer.WriteLine("InhibitTimePolicy = GasInhibitTimePolicy.DurationContinues,");
            writer.WriteLine($"InhibitedPeriodPolicy = {(row.Period.IsDefined ? "GasInhibitedPeriodPolicy.SkipExecution" : "GasInhibitedPeriodPolicy.None")},");
            writer.WriteLine("MissedPeriodPolicy = GasMissedPeriodPolicy.SkipNoCatchUp,");
            writer.WriteLine($"ExecuteOnApplication = {(row.Period.IsDefined && row.Period.FirstTrigger ? 1 : 0)},");
        }

        /// <summary>
        /// 写入所有 flat payload 数组工厂。
        /// </summary>
        private static void WritePayloadFactories(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteCaptureFactory(writer, plan);
            writer.WriteLine();
            WriteModifierFactory(writer, plan);
            writer.WriteLine();
            WriteDirectNodeFactory(writer, plan);
            writer.WriteLine();
            WriteCueFactory(writer, plan);
            writer.WriteLine();
            WriteValueViewFactory(writer, plan);
            writer.WriteLine();
            WriteEvaluatorFactory(writer, plan);
            writer.WriteLine();
            WriteTargetDataFactory(writer, plan);
            writer.WriteLine();
            WriteContextFactory(writer, plan);
        }

        /// <summary>
        /// 写入 9203 Source Attack Snapshot capture descriptor。
        /// </summary>
        private static void WriteCaptureFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasCaptureDescriptorBlob", "CreateCaptureDescriptors", "创建 flat capture descriptors。");
            foreach (var capture in plan.Captures)
            {
                writer.WriteLine("new GasCaptureDescriptorBlob");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"CaptureOrdinal = {capture.CaptureOrdinal},");
                writer.WriteLine("Owner = GasCaptureOwner.Source,");
                writer.WriteLine("Binding = GasCaptureBinding.Snapshot,");
                writer.WriteLine("Phase = GasCapturePhase.SourceSpecProjection,");
                writer.WriteLine("LiveScope = GasLiveCaptureScope.None,");
                writer.WriteLine("GonePolicy = GasCaptureGonePolicy.RejectApplication,");
                writer.WriteLine("ValueView = GasAttributeValueView.Base,");
                writer.WriteLine($"AttributeLayoutIndex = {capture.AttributeLayoutIndex},");
                writer.WriteLine("ConsumerNodeOrdinal = 0,");
                writer.WriteLine("ConsumerFieldOrdinal = 0,");
                writer.Indent--;
                writer.WriteLine("},");
            }
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入 flat Modifier definitions。
        /// </summary>
        private static void WriteModifierFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasModifierDefinitionBlob", "CreateModifiers", "创建 flat Modifier definitions。");
            foreach (var modifier in plan.Modifiers)
            {
                writer.WriteLine("new GasModifierDefinitionBlob");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"AttributeLayoutIndex = {modifier.AttributeLayoutIndex},");
                writer.WriteLine($"Operation = GasModifierOperation.{modifier.Operation},");
                writer.WriteLine($"EvaluatorProgramRange = Range({modifier.EvaluatorStart}, {modifier.EvaluatorCount}),");
                writer.WriteLine($"CaptureRange = Range({modifier.CaptureStart}, {modifier.CaptureCount}),");
                writer.Indent--;
                writer.WriteLine("},");
            }
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入 Ability direct-effect program nodes。
        /// </summary>
        private static void WriteDirectNodeFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasDirectEffectProgramNodeBlob", "CreateDirectEffectProgramNodes", "创建 Ability direct-effect program nodes。");
            foreach (var ability in plan.Model.Abilities)
            {
                writer.WriteLine($"new GasDirectEffectProgramNodeBlob {{ NodeOrdinal = 0, EffectDefinitionId = {ability.PrimaryGameplayEffectCode}, MaximumTargetCount = 1, MaximumOutputCount = 1 }},");
            }
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入 Cue 引用及其四阶段 flags。
        /// </summary>
        private static void WriteCueFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasCueReferenceBlob", "CreateCueReferences", "创建按 definition 分段的 Cue references。");
            foreach (var cue in plan.Cues)
                writer.WriteLine($"new GasCueReferenceBlob {{ CueDefinitionId = {cue.CueId}, CueDefinitionOrdinal = {cue.Ordinal}, Phases = {CueFlags(cue.Flags)} }},");
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入 evaluator ValueView descriptors。
        /// </summary>
        private static void WriteValueViewFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasValueViewDescriptorBlob", "CreateValueViews", "创建 evaluator ValueView descriptors。");
            foreach (var view in plan.ValueViews)
                writer.WriteLine($"new GasValueViewDescriptorBlob {{ AttributeLayoutIndex = {view.AttributeLayoutIndex}, ValueView = GasAttributeValueView.{view.ValueView} }},");
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入 canonical postfix evaluator instructions。
        /// </summary>
        private static void WriteEvaluatorFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasEvaluatorInstructionBlob", "CreateEvaluatorInstructions", "创建 canonical postfix evaluator instructions。");
            foreach (var instruction in plan.Evaluators)
            {
                writer.WriteLine("new GasEvaluatorInstructionBlob");
                writer.WriteLine("{");
                writer.Indent++;
                writer.WriteLine($"Opcode = GasEvaluatorOpcode.{instruction.Opcode},");
                if (instruction.OperandIndex != 0)
                    writer.WriteLine($"OperandIndex = {instruction.OperandIndex},");
                if (instruction.Opcode == "PushConstant")
                    writer.WriteLine($"ConstantValue = {FloatLiteral(instruction.ConstantValue)},");
                writer.Indent--;
                writer.WriteLine("},");
            }
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入每个 Effect 的 StableAsc TargetData descriptor。
        /// </summary>
        private static void WriteTargetDataFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasTargetDataDescriptorBlob", "CreateTargetDataDescriptors", "创建每个 Effect 的 StableAsc TargetData descriptor。");
            foreach (var _ in plan.Effects)
                writer.WriteLine("new GasTargetDataDescriptorBlob { Variant = GasTargetDataVariant.StableAsc, FieldOrdinal = 0, Required = 1 },");
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入每个 Effect 的 causality 与 Avatar binding context fields。
        /// </summary>
        private static void WriteContextFactory(IndentedWriter writer, CatalogEmissionPlan plan)
        {
            WriteArrayFactoryStart(writer, "GasEffectContextFieldDescriptorBlob", "CreateEffectContextFieldDescriptors", "创建每个 Effect 的必需 context fields。");
            foreach (var _ in plan.Effects)
            {
                writer.WriteLine("new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.CausalityId, FieldOrdinal = 0, Required = 1 },");
                writer.WriteLine("new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.SourceAvatarBindingGeneration, FieldOrdinal = 1, Required = 1 },");
                writer.WriteLine("new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.TargetAvatarBindingGeneration, FieldOrdinal = 2, Required = 1 },");
            }
            WriteArrayFactoryEnd(writer);
        }

        /// <summary>
        /// 写入一个 generated 数组工厂的公共前半段。
        /// </summary>
        private static void WriteArrayFactoryStart(
            IndentedWriter writer,
            string elementType,
            string methodName,
            string summary)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine($"/// {summary}");
            writer.WriteLine("/// </summary>");
            writer.WriteLine($"private static {elementType}[] {methodName}()");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"return new {elementType}[]");
            writer.WriteLine("{");
            writer.Indent++;
        }

        /// <summary>
        /// 写入一个 generated 数组工厂的公共结束段。
        /// </summary>
        private static void WriteArrayFactoryEnd(IndentedWriter writer)
        {
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入四维 target policy 初始化器。
        /// </summary>
        private static void WriteTargetPolicy(IndentedWriter writer, in AutoChessTargetPolicyRow policy)
        {
            writer.WriteLine("TargetPolicy = new GasTargetPolicyBlob");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"LogicalTarget = (GasLogicalTargetPolicy){policy.LogicalTarget},");
            writer.WriteLine($"Avatar = (GasAvatarTargetPolicy){policy.Avatar},");
            writer.WriteLine($"Spatial = (GasSpatialTargetPolicy){policy.Spatial},");
            writer.WriteLine($"Life = (GasTargetLifePolicy){policy.Life},");
            writer.Indent--;
            writer.WriteLine("},");
        }

        /// <summary>
        /// 写入 definition maxima，参数顺序与 schema 关注点一致。
        /// </summary>
        private static void WriteMaxima(
            IndentedWriter writer,
            int modifierCount,
            int cueCount,
            int directNodeCount,
            int valueViewCount,
            int evaluatorCount,
            int targetDataCount,
            int contextCount,
            int captureCount,
            int targetCount,
            int plannedApplicationCount)
        {
            writer.WriteLine("Maxima = new GasDefinitionMaxima");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine($"MaximumTargetCount = {targetCount},");
            writer.WriteLine($"MaximumPlannedApplicationCount = {plannedApplicationCount},");
            writer.WriteLine($"MaximumCaptureDescriptorCount = {captureCount},");
            writer.WriteLine($"MaximumModifierCount = {modifierCount},");
            writer.WriteLine($"MaximumDirectProgramNodeCount = {directNodeCount},");
            writer.WriteLine($"MaximumDirectProgramOutputCount = {directNodeCount},");
            writer.WriteLine($"MaximumCueCount = {cueCount},");
            writer.WriteLine($"MaximumValueViewCount = {valueViewCount},");
            writer.WriteLine($"MaximumEvaluatorInstructionCount = {evaluatorCount},");
            writer.WriteLine($"MaximumTargetDataCount = {targetDataCount},");
            writer.WriteLine($"MaximumEffectContextFieldCount = {contextCount},");
            writer.Indent--;
            writer.WriteLine("},");
        }

        /// <summary>
        /// 写入 generated range helper，避免重复构造器噪声。
        /// </summary>
        private static void WriteRangeFactory(IndentedWriter writer)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 创建一个 generated Catalog 半开区间。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("private static GasCatalogRange Range(int start, int count)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return new GasCatalogRange { Start = start, Count = count };");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入对外稳定 ID、场景阈值与单位模板 glue。
        /// </summary>
        private static void WriteGeneratedConfig(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 暴露 AutoChess generated 稳定 ID 与场景数据。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public static class AutoChessGeneratedConfig");
            writer.WriteLine("{");
            writer.Indent++;
            WriteStableConstants(writer, model);
            writer.WriteLine();
            WriteScenarioValue(writer, model.ValidationScenario);
            writer.WriteLine();
            WriteBaseUnitSpawnPlans(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入由 Luban 解析出的稳定 ID 与非玩法房间文案。
        /// </summary>
        private static void WriteStableConstants(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine("public const string RoomIdPrefix = \"room-standard-duel-x\";");
            writer.WriteLine("public const string RoomDisplayName = \"标准双人自走棋对局\";");
            writer.WriteLine("public const string PlayerId = \"player-a\";");
            writer.WriteLine("public const string EnemyId = \"player-b\";");
            writer.WriteLine("public const string PlayerDisplayName = \"玩家A\";");
            writer.WriteLine("public const string EnemyDisplayName = \"玩家B\";");
            writer.WriteLine();
            writer.WriteLine($"public const int AttributeSetCombat = {model.AttributeSetCombat};");
            writer.WriteLine($"public const int AttributeHealth = {model.AttributeHealth};");
            writer.WriteLine($"public const int AttributeEnergy = {model.AttributeEnergy};");
            writer.WriteLine($"public const int AttributeAttack = {model.AttributeAttack};");
            writer.WriteLine($"public const int AbilityPlayerAttack = {model.AbilityPlayerAttack};");
            writer.WriteLine($"public const int AbilityEnemyAttack = {model.AbilityEnemyAttack};");
            writer.WriteLine($"public const int AbilityPlayerExecute = {model.AbilityPlayerExecute};");
            writer.WriteLine($"public const int AbilityPlayerPoison = {model.AbilityPlayerPoison};");
            writer.WriteLine($"public const int GameplayEffectPlayerAttackDamage = {model.GameplayEffectPlayerAttackDamage};");
            writer.WriteLine($"public const int GameplayEffectEnemyAttackDamage = {model.GameplayEffectEnemyAttackDamage};");
            writer.WriteLine($"public const int GameplayEffectPlayerExecute = {model.GameplayEffectPlayerExecute};");
            writer.WriteLine($"public const int GameplayEffectPlayerPoison = {model.GameplayEffectPlayerPoison};");
        }

        /// <summary>
        /// 写入 generated 场景 profile 常量表达式。
        /// </summary>
        private static void WriteScenarioValue(IndentedWriter writer, AutoChessDemoScenarioModel scenario)
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 返回 generated 验证场景阈值。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public static AutoChessGeneratedScenarioProfile ValidationScenario => new AutoChessGeneratedScenarioProfile(");
            writer.Indent++;
            writer.WriteLine($"{scenario.Scale},");
            writer.WriteLine($"{scenario.MaxTicks},");
            writer.WriteLine($"{FloatLiteral(scenario.HealthMultiplier)},");
            writer.WriteLine($"{scenario.ExpectedWinner},");
            writer.WriteLine($"{scenario.MinAcceptedCommands},");
            writer.WriteLine($"{scenario.MinAttributeChanges},");
            writer.WriteLine($"{scenario.MinExecutionOutputs},");
            writer.WriteLine($"{scenario.MinCueRequests},");
            writer.WriteLine($"{scenario.MinActiveEffectSlots},");
            writer.WriteLine($"{scenario.MinPeriodTickDamageFacts},");
            writer.WriteLine($"{scenario.MinActiveMutationCommands},");
            writer.WriteLine($"{scenario.MinActiveMutationOwnerGroups},");
            writer.WriteLine($"{scenario.MaxActiveMutationEstimatedRandomLookups},");
            writer.WriteLine($"{scenario.MaxActiveMutationOwnerResourceLookups},");
            writer.WriteLine($"{scenario.MaxActiveMutationMigrationCarriers});");
            writer.Indent--;
        }

        /// <summary>
        /// 写入所有 generated 单位模板与按索引访问器。
        /// </summary>
        private static void WriteBaseUnitSpawnPlans(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine($"public const int BaseUnitSpawnPlanCount = {model.BaseUnits.Count};");
            writer.WriteLine();
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// 按稳定索引返回 generated 单位模板。");
            writer.WriteLine("/// </summary>");
            writer.WriteLine("public static AutoChessGeneratedUnitSpawnPlan GetBaseUnitSpawnPlan(int index)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return index switch");
            writer.WriteLine("{");
            writer.Indent++;
            for (var index = 0; index < model.BaseUnits.Count; index++)
            {
                writer.WriteLine($"{index} =>");
                writer.Indent++;
                WriteUnit(writer, model.BaseUnits[index]);
                writer.Indent--;
            }
            writer.WriteLine("_ => throw new ArgumentOutOfRangeException(nameof(index), index, \"Unknown AutoChess base unit spawn plan index.\"),");
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        /// <summary>
        /// 写入一个 generated 单位模板表达式。
        /// </summary>
        private static void WriteUnit(IndentedWriter writer, in AutoChessDemoUnitModel unit)
        {
            writer.WriteLine("new AutoChessGeneratedUnitSpawnPlan(");
            writer.Indent++;
            writer.WriteLine($"{StringLiteral(unit.Id)},");
            writer.WriteLine($"{StringLiteral(unit.DisplayName)},");
            writer.WriteLine($"{StringLiteral(unit.ArchetypeName)},");
            writer.WriteLine($"{unit.Team},");
            writer.WriteLine($"{unit.Slot},");
            writer.WriteLine($"{FloatLiteral(unit.Health)},");
            writer.WriteLine($"{FloatLiteral(unit.Energy)},");
            writer.WriteLine($"{FloatLiteral(unit.Attack)},");
            writer.WriteLine($"{unit.PrimaryAbilityCode},");
            writer.WriteLine($"{unit.FinisherAbilityCode},");
            writer.WriteLine($"{unit.ActiveAbilityCode},");
            writer.WriteLine($"{unit.ActiveCastInterval},");
            writer.WriteLine($"{unit.ActiveCastFrameOffset},");
            writer.WriteLine($"{FloatLiteral(unit.FinisherHealthThreshold)},");
            writer.WriteLine($"{unit.PrimaryTargetPolicy},");
            writer.WriteLine($"{unit.FinisherTargetPolicy}),");
            writer.Indent--;
        }

        /// <summary>
        /// 将 float 写成区域无关的 C# 9 literal。
        /// </summary>
        private static string FloatLiteral(float value)
        {
            return value.ToString("0.########", CultureInfo.InvariantCulture) + "f";
        }

        /// <summary>
        /// 将字符串写成转义后的 C# literal。
        /// </summary>
        private static string StringLiteral(string value)
        {
            if (value == null)
                return "string.Empty";
            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }

        /// <summary>
        /// 将 Cue 位掩码写成可审查的 enum 组合表达式。
        /// </summary>
        private static string CueFlags(int flags)
        {
            var names = new List<string>(4);
            if ((flags & 1) != 0) names.Add("GasCuePhaseFlags.OnActive");
            if ((flags & 2) != 0) names.Add("GasCuePhaseFlags.WhileActive");
            if ((flags & 4) != 0) names.Add("GasCuePhaseFlags.Executed");
            if ((flags & 8) != 0) names.Add("GasCuePhaseFlags.Removed");
            return string.Join(" | ", names);
        }

        /// <summary>
        /// 创建缺失的 Unity meta，保持 generated artifact GUID 稳定。
        /// </summary>
        private static void EnsureUnityMeta(string path)
        {
            var metaPath = path + ".meta";
            if (File.Exists(metaPath))
                return;
            File.WriteAllText(
                metaPath,
                "fileFormatVersion: 2\n"
                + "guid: " + CreateGuid() + "\n"
                + "MonoImporter:\n"
                + "  externalObjects: {}\n"
                + "  serializedVersion: 2\n"
                + "  defaultReferences: []\n"
                + "  executionOrder: 0\n"
                + "  icon: {instanceID: 0}\n"
                + "  userData: \n"
                + "  assetBundleName: \n"
                + "  assetBundleVariant: \n");
        }

        /// <summary>
        /// 返回该唯一 generated artifact 的固定 Unity GUID，避免 candidate 物理路径改变 asset 身份。
        /// </summary>
        private static string CreateGuid()
        {
            return "26696cca26696cca26696cca26696cca";
        }

        /// <summary>
        /// 把已校验模型编译成 generated flat arrays 与 per-definition ranges。
        /// </summary>
        private sealed class CatalogEmissionPlan
        {
            private CatalogEmissionPlan(AutoChessRuntimeV1CatalogModel model)
            {
                Model = model;
            }

            public AutoChessRuntimeV1CatalogModel Model { get; }
            public EffectEmissionPlan[] Effects { get; private set; }
            public List<CaptureEmissionPlan> Captures { get; } = new List<CaptureEmissionPlan>();
            public List<ModifierEmissionPlan> Modifiers { get; } = new List<ModifierEmissionPlan>();
            public List<CueEmissionPlan> Cues { get; } = new List<CueEmissionPlan>();
            public List<ValueViewEmissionPlan> ValueViews { get; } = new List<ValueViewEmissionPlan>();
            public List<EvaluatorEmissionPlan> Evaluators { get; } = new List<EvaluatorEmissionPlan>();

            /// <summary>
            /// 为每个 Effect 编译唯一 modifier/evaluator/cue 片段。
            /// </summary>
            public static CatalogEmissionPlan Create(AutoChessRuntimeV1CatalogModel model)
            {
                var plan = new CatalogEmissionPlan(model ?? throw new ArgumentNullException(nameof(model)));
                var effectsById = model.Effects.ToDictionary(row => row.GameplayEffectCode);
                var effectPlans = new List<EffectEmissionPlan>(model.Effects.Length);
                for (var index = 0; index < model.Effects.Length; index++)
                    effectPlans.Add(plan.CompileEffect(model.Effects[index], effectsById, index));
                plan.Effects = effectPlans.ToArray();
                return plan;
            }

            /// <summary>
            /// 编译单个 Effect，并记录所有 flat array 起点与数量。
            /// </summary>
            private EffectEmissionPlan CompileEffect(
                in AutoChessGameplayEffectRow effect,
                IReadOnlyDictionary<int, AutoChessGameplayEffectRow> effectsById,
                int effectIndex)
            {
                var captureStart = Captures.Count;
                var modifierStart = Modifiers.Count;
                var evaluatorStart = Evaluators.Count;
                var valueViewStart = ValueViews.Count;
                if (effect.Evaluator.Kind == 1)
                    CompileMissingHealthEvaluator(in effect);
                else if (effect.Evaluator.Kind == 2)
                    CompileAttackStackCountEvaluator(in effect);
                else
                    CompileFixedModifier(in effect, effectsById);
                var cueStart = Cues.Count;
                CompileCues(in effect);
                return new EffectEmissionPlan(
                    effect,
                    effect.Evaluator.Kind == 1 ? "InstantExecution" : effect.Duration.IsDefined ? "Duration" : "Instant",
                    captureStart,
                    Captures.Count - captureStart,
                    modifierStart,
                    Modifiers.Count - modifierStart,
                    evaluatorStart,
                    Evaluators.Count - evaluatorStart,
                    valueViewStart,
                    ValueViews.Count - valueViewStart,
                    cueStart,
                    Cues.Count - cueStart,
                    effectIndex,
                    effectIndex * 3,
                    effect.Evaluator.Kind == 1
                        ? "GasAttributeValueViewMask.Base | GasAttributeValueViewMask.Current | GasAttributeValueViewMask.DefinitionMaxValue"
                        : "GasAttributeValueViewMask.None");
            }

            /// <summary>
            /// 编译普通 Modifier；period root 会直接展开其唯一 child modifier。
            /// </summary>
            private void CompileFixedModifier(
                in AutoChessGameplayEffectRow effect,
                IReadOnlyDictionary<int, AutoChessGameplayEffectRow> effectsById)
            {
                var modifiers = effect.Modifiers;
                if (modifiers.Length == 0 && effect.Period.IsDefined)
                {
                    modifiers = effect.Period.EffectCodes
                        .SelectMany(id => effectsById[id].Modifiers)
                        .ToArray();
                }
                if (modifiers.Length != 1)
                    throw new InvalidDataException($"[AutoChessCatalog] Effect {effect.GameplayEffectCode} must compile to exactly one modifier.");
                var modifier = modifiers[0];
                var evaluatorStart = Evaluators.Count;
                var magnitude = modifier.Operation == 3 ? -modifier.Magnitude : modifier.Magnitude;
                Evaluators.Add(new EvaluatorEmissionPlan("PushConstant", 0, magnitude));
                Modifiers.Add(new ModifierEmissionPlan(
                    ResolveAttributeLayoutIndex(modifier.AttributeSetCode, modifier.AttributeCode),
                    ModifierOperation(modifier.Operation),
                    evaluatorStart,
                    1,
                    Captures.Count,
                    0));
            }

            /// <summary>
            /// 编译 TargetMissingHealth 为 3 个 ValueView 与 13 条 postfix 指令。
            /// </summary>
            private void CompileMissingHealthEvaluator(in AutoChessGameplayEffectRow effect)
            {
                var evaluator = effect.Evaluator;
                var layoutIndex = ResolveAttributeLayoutIndex(
                    evaluator.AttributeSetCode,
                    evaluator.AttributeCode);
                ValueViews.Add(new ValueViewEmissionPlan(layoutIndex, "Base"));
                ValueViews.Add(new ValueViewEmissionPlan(layoutIndex, "Current"));
                ValueViews.Add(new ValueViewEmissionPlan(layoutIndex, "DefinitionMaxValue"));
                var evaluatorStart = Evaluators.Count;
                AddInstruction("PushValueView", 2);
                AddInstruction("PushValueView", 0);
                AddInstruction("Subtract");
                AddConstant(0f);
                AddInstruction("Maximum");
                AddConstant(evaluator.Coefficient);
                AddInstruction("Multiply");
                AddConstant(evaluator.BaseValue);
                AddInstruction("Add");
                AddConstant(evaluator.Minimum);
                AddConstant(evaluator.Maximum);
                AddInstruction("Clamp");
                AddInstruction("Negate");
                Modifiers.Add(new ModifierEmissionPlan(
                    layoutIndex,
                    "Add",
                    evaluatorStart,
                    13,
                    Captures.Count,
                    0));
            }

            /// <summary>
            /// 编译 Source Attack Snapshot × coefficient × current stack count 的 period 伤害公式。
            /// </summary>
            private void CompileAttackStackCountEvaluator(in AutoChessGameplayEffectRow effect)
            {
                var evaluator = effect.Evaluator;
                var inputLayoutIndex = ResolveAttributeLayoutIndex(
                    evaluator.AttributeSetCode,
                    evaluator.AttributeCode);
                var modifier = effect.Modifiers[0];
                var outputLayoutIndex = ResolveAttributeLayoutIndex(
                    modifier.AttributeSetCode,
                    modifier.AttributeCode);
                var captureStart = Captures.Count;
                Captures.Add(new CaptureEmissionPlan(0, inputLayoutIndex));
                var evaluatorStart = Evaluators.Count;
                AddInstruction("PushCapture");
                AddConstant(evaluator.Coefficient);
                AddInstruction("Multiply");
                AddInstruction("PushStackCount");
                AddInstruction("Multiply");
                AddInstruction("Negate");
                Modifiers.Add(new ModifierEmissionPlan(
                    outputLayoutIndex,
                    "Add",
                    evaluatorStart,
                    6,
                    captureStart,
                    1));
            }

            /// <summary>
            /// 合并同一 Cue ID 的阶段并生成 definition-local ordinal。
            /// </summary>
            private void CompileCues(in AutoChessGameplayEffectRow effect)
            {
                var flagsByCue = new Dictionary<int, int>();
                AddCueFlags(flagsByCue, effect.CueOnApply, effect.Duration.IsDefined ? 1 : 4);
                AddCueFlags(flagsByCue, effect.CueOnTick, 2);
                AddCueFlags(flagsByCue, effect.CueOnAdd, 1);
                AddCueFlags(flagsByCue, effect.CueOnActivate, 1);
                AddCueFlags(flagsByCue, effect.CueOnRemove, 8);
                AddCueFlags(flagsByCue, effect.CueOnDeactivate, 8);
                var ordinal = 0;
                foreach (var pair in flagsByCue.OrderBy(pair => pair.Key))
                {
                    Cues.Add(new CueEmissionPlan(pair.Key, ordinal, pair.Value));
                    ordinal++;
                }
            }

            /// <summary>
            /// 合并一组 Cue ID 的阶段位。
            /// </summary>
            private static void AddCueFlags(
                IDictionary<int, int> flagsByCue,
                IEnumerable<int> cueIds,
                int flags)
            {
                foreach (var cueId in cueIds)
                {
                    flagsByCue.TryGetValue(cueId, out var existing);
                    flagsByCue[cueId] = existing | flags;
                }
            }

            /// <summary>
            /// 解析 AttributeSet+Attribute 到 generated dense layout index。
            /// </summary>
            private int ResolveAttributeLayoutIndex(int attributeSetCode, int attributeCode)
            {
                for (var index = 0; index < Model.Attributes.Length; index++)
                {
                    var attribute = Model.Attributes[index];
                    if (attribute.AttributeSetCode == attributeSetCode && attribute.AttributeCode == attributeCode)
                        return index;
                }
                throw new InvalidDataException($"[AutoChessCatalog] Unknown attribute {attributeSetCode}:{attributeCode}.");
            }

            /// <summary>
            /// 追加一条不带常量的 evaluator 指令。
            /// </summary>
            private void AddInstruction(string opcode, int operandIndex = 0)
            {
                Evaluators.Add(new EvaluatorEmissionPlan(opcode, operandIndex, 0f));
            }

            /// <summary>
            /// 追加一条 PushConstant evaluator 指令。
            /// </summary>
            private void AddConstant(float value)
            {
                Evaluators.Add(new EvaluatorEmissionPlan("PushConstant", 0, value));
            }

            /// <summary>
            /// 将 Luban Modifier operation 映射到 Runtime v1 闭集名称。
            /// </summary>
            private static string ModifierOperation(int operation)
            {
                return operation switch
                {
                    0 => "Add",
                    1 => "Multiply",
                    2 => "Override",
                    3 => "Add",
                    4 => "Divide",
                    _ => throw new InvalidDataException($"[AutoChessCatalog] Unsupported modifier operation: {operation}"),
                };
            }
        }

        /// <summary>
        /// 保存一个 generated Effect 的全部 flat-array ranges。
        /// </summary>
        private sealed class EffectEmissionPlan
        {
            public EffectEmissionPlan(
                AutoChessGameplayEffectRow row,
                string lifetime,
                int captureStart,
                int captureCount,
                int modifierStart,
                int modifierCount,
                int evaluatorStart,
                int evaluatorCount,
                int valueViewStart,
                int valueViewCount,
                int cueStart,
                int cueCount,
                int targetDataStart,
                int contextStart,
                string requiredValueViews)
            {
                Row = row;
                Lifetime = lifetime;
                CaptureStart = captureStart;
                CaptureCount = captureCount;
                ModifierStart = modifierStart;
                ModifierCount = modifierCount;
                EvaluatorStart = evaluatorStart;
                EvaluatorCount = evaluatorCount;
                ValueViewStart = valueViewStart;
                ValueViewCount = valueViewCount;
                CueStart = cueStart;
                CueCount = cueCount;
                TargetDataStart = targetDataStart;
                ContextStart = contextStart;
                RequiredValueViews = requiredValueViews;
            }

            public AutoChessGameplayEffectRow Row { get; }
            public string Lifetime { get; }
            public int CaptureStart { get; }
            public int CaptureCount { get; }
            public int ModifierStart { get; }
            public int ModifierCount { get; }
            public int EvaluatorStart { get; }
            public int EvaluatorCount { get; }
            public int ValueViewStart { get; }
            public int ValueViewCount { get; }
            public int CueStart { get; }
            public int CueCount { get; }
            public int TargetDataStart { get; }
            public int ContextStart { get; }
            public string RequiredValueViews { get; }
        }

        /// <summary>
        /// 保存一个 generated Modifier flat-array 元素。
        /// </summary>
        private readonly struct ModifierEmissionPlan
        {
            public ModifierEmissionPlan(
                int attributeLayoutIndex,
                string operation,
                int evaluatorStart,
                int evaluatorCount,
                int captureStart,
                int captureCount)
            {
                AttributeLayoutIndex = attributeLayoutIndex;
                Operation = operation;
                EvaluatorStart = evaluatorStart;
                EvaluatorCount = evaluatorCount;
                CaptureStart = captureStart;
                CaptureCount = captureCount;
            }

            public int AttributeLayoutIndex { get; }
            public string Operation { get; }
            public int EvaluatorStart { get; }
            public int EvaluatorCount { get; }
            public int CaptureStart { get; }
            public int CaptureCount { get; }
        }

        /// <summary>
        /// 保存一个 generated Source Snapshot capture flat-array 元素。
        /// </summary>
        private readonly struct CaptureEmissionPlan
        {
            public CaptureEmissionPlan(int captureOrdinal, int attributeLayoutIndex)
            {
                CaptureOrdinal = captureOrdinal;
                AttributeLayoutIndex = attributeLayoutIndex;
            }

            public int CaptureOrdinal { get; }
            public int AttributeLayoutIndex { get; }
        }

        /// <summary>
        /// 保存一个 generated Cue flat-array 元素。
        /// </summary>
        private readonly struct CueEmissionPlan
        {
            public CueEmissionPlan(int cueId, int ordinal, int flags)
            {
                CueId = cueId;
                Ordinal = ordinal;
                Flags = flags;
            }

            public int CueId { get; }
            public int Ordinal { get; }
            public int Flags { get; }
        }

        /// <summary>
        /// 保存一个 generated ValueView flat-array 元素。
        /// </summary>
        private readonly struct ValueViewEmissionPlan
        {
            public ValueViewEmissionPlan(int attributeLayoutIndex, string valueView)
            {
                AttributeLayoutIndex = attributeLayoutIndex;
                ValueView = valueView;
            }

            public int AttributeLayoutIndex { get; }
            public string ValueView { get; }
        }

        /// <summary>
        /// 保存一条 generated postfix evaluator 指令。
        /// </summary>
        private readonly struct EvaluatorEmissionPlan
        {
            public EvaluatorEmissionPlan(string opcode, int operandIndex, float constantValue)
            {
                Opcode = opcode;
                OperandIndex = operandIndex;
                ConstantValue = constantValue;
            }

            public string Opcode { get; }
            public int OperandIndex { get; }
            public float ConstantValue { get; }
        }
    }
}
