using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace GAS.Editor
{
    internal sealed class AutoChessDemoConfigPhase : GasCodeGenPhaseBase
    {
        public override string PhaseName => "AutoChessDemoConfig";

        public override IReadOnlyList<string> OutputFileNames { get; } =
            new[] { "../../../AutoChessDemo/Generated/AutoChessGeneratedConfig.gen.cs" };

        public override bool RequiresRows => false;

        public override void Execute(GasCodeGenContext context, GasCodeGenManifest manifest)
        {
            var path = GetOutputPath(context, OutputFileNames[0]);
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            AddRuntimeManifest(manifest, PhaseName, path);
            var model = AutoChessDemoConfigModel.FromLubanJson(context);

            using var stream = new StreamWriter(path);
            using var writer = new IndentedWriter(stream);
            WriteAutoChessHeader(writer);
            writer.WriteLine("namespace GAS.AutoChessDemo");
            writer.WriteLine("{");
            writer.Indent++;
            WriteScenarioProfile(writer);
            writer.WriteLine();
            WriteGeneratedExecuteDamageCalculation(writer);
            writer.WriteLine();
            WriteGeneratedExecutionEvaluator(writer);
            writer.WriteLine();
            WriteGeneratedUnitSpawnPlan(writer);
            writer.WriteLine();
            WriteGeneratedConfig(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
            EnsureUnityMeta(path);
        }

        private static void WriteAutoChessHeader(IndentedWriter writer)
        {
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using System;");
            writer.WriteLine("using Unity.Mathematics;");
            writer.WriteLine();
        }

        private static void WriteScenarioProfile(IndentedWriter writer)
        {
            writer.WriteLine("public readonly struct AutoChessGeneratedScenarioProfile");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public readonly int Scale;");
            writer.WriteLine("public readonly int MaxTicks;");
            writer.WriteLine("public readonly int PostVictoryFlushTicks;");
            writer.WriteLine("public readonly int ProcessWarmupRuns;");
            writer.WriteLine("public readonly float HealthMultiplier;");
            writer.WriteLine("public readonly AutoChessTeam ExpectedWinner;");
            writer.WriteLine("public readonly int MinDriverIssuedCommands;");
            writer.WriteLine("public readonly int MinAttributeChanges;");
            writer.WriteLine("public readonly int MinExecutionOutputs;");
            writer.WriteLine("public readonly int MinCueRequests;");
            writer.WriteLine("public readonly int MinActiveEffectSlots;");
            writer.WriteLine("public readonly int MinPeriodTickDamageFacts;");
            writer.WriteLine("public readonly int MinActiveMutationCommands;");
            writer.WriteLine("public readonly int MinActiveMutationOwnerGroups;");
            writer.WriteLine("public readonly int MaxActiveMutationEstimatedRandomLookups;");
            writer.WriteLine("public readonly int MaxActiveMutationOwnerResourceLookups;");
            writer.WriteLine("public readonly int MaxActiveMutationMigrationCarriers;");
            writer.WriteLine();
            writer.WriteLine("public AutoChessGeneratedScenarioProfile(");
            writer.Indent++;
            writer.WriteLine("int scale,");
            writer.WriteLine("int maxTicks,");
            writer.WriteLine("int postVictoryFlushTicks,");
            writer.WriteLine("int processWarmupRuns,");
            writer.WriteLine("float healthMultiplier,");
            writer.WriteLine("AutoChessTeam expectedWinner,");
            writer.WriteLine("int minDriverIssuedCommands,");
            writer.WriteLine("int minAttributeChanges,");
            writer.WriteLine("int minExecutionOutputs,");
            writer.WriteLine("int minCueRequests,");
            writer.WriteLine("int minActiveEffectSlots,");
            writer.WriteLine("int minPeriodTickDamageFacts,");
            writer.WriteLine("int minActiveMutationCommands,");
            writer.WriteLine("int minActiveMutationOwnerGroups,");
            writer.WriteLine("int maxActiveMutationEstimatedRandomLookups,");
            writer.WriteLine("int maxActiveMutationOwnerResourceLookups,");
            writer.WriteLine("int maxActiveMutationMigrationCarriers)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Scale = scale;");
            writer.WriteLine("MaxTicks = maxTicks;");
            writer.WriteLine("PostVictoryFlushTicks = postVictoryFlushTicks;");
            writer.WriteLine("ProcessWarmupRuns = processWarmupRuns;");
            writer.WriteLine("HealthMultiplier = healthMultiplier;");
            writer.WriteLine("ExpectedWinner = expectedWinner;");
            writer.WriteLine("MinDriverIssuedCommands = minDriverIssuedCommands;");
            writer.WriteLine("MinAttributeChanges = minAttributeChanges;");
            writer.WriteLine("MinExecutionOutputs = minExecutionOutputs;");
            writer.WriteLine("MinCueRequests = minCueRequests;");
            writer.WriteLine("MinActiveEffectSlots = minActiveEffectSlots;");
            writer.WriteLine("MinPeriodTickDamageFacts = minPeriodTickDamageFacts;");
            writer.WriteLine("MinActiveMutationCommands = minActiveMutationCommands;");
            writer.WriteLine("MinActiveMutationOwnerGroups = minActiveMutationOwnerGroups;");
            writer.WriteLine("MaxActiveMutationEstimatedRandomLookups = maxActiveMutationEstimatedRandomLookups;");
            writer.WriteLine("MaxActiveMutationOwnerResourceLookups = maxActiveMutationOwnerResourceLookups;");
            writer.WriteLine("MaxActiveMutationMigrationCarriers = maxActiveMutationMigrationCarriers;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteGeneratedExecuteDamageCalculation(IndentedWriter writer)
        {
            writer.WriteLine("public readonly struct AutoChessGeneratedExecuteDamageCalculation");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public readonly int GameplayEffectCode;");
            writer.WriteLine("public readonly int CalculationCode;");
            writer.WriteLine("public readonly int OutputKey;");
            writer.WriteLine("public readonly int HealthAttrSetCode;");
            writer.WriteLine("public readonly int HealthAttrCode;");
            writer.WriteLine("public readonly float BaseDamage;");
            writer.WriteLine("public readonly float MissingHealthCoefficient;");
            writer.WriteLine("public readonly float MinDamage;");
            writer.WriteLine("public readonly float MaxDamage;");
            writer.WriteLine();
            writer.WriteLine("public AutoChessGeneratedExecuteDamageCalculation(");
            writer.Indent++;
            writer.WriteLine("int gameplayEffectCode,");
            writer.WriteLine("int calculationCode,");
            writer.WriteLine("int outputKey,");
            writer.WriteLine("int healthAttrSetCode,");
            writer.WriteLine("int healthAttrCode,");
            writer.WriteLine("float baseDamage,");
            writer.WriteLine("float missingHealthCoefficient,");
            writer.WriteLine("float minDamage,");
            writer.WriteLine("float maxDamage)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("GameplayEffectCode = gameplayEffectCode;");
            writer.WriteLine("CalculationCode = calculationCode;");
            writer.WriteLine("OutputKey = outputKey;");
            writer.WriteLine("HealthAttrSetCode = healthAttrSetCode;");
            writer.WriteLine("HealthAttrCode = healthAttrCode;");
            writer.WriteLine("BaseDamage = baseDamage;");
            writer.WriteLine("MissingHealthCoefficient = missingHealthCoefficient;");
            writer.WriteLine("MinDamage = minDamage;");
            writer.WriteLine("MaxDamage = maxDamage;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteGeneratedExecutionEvaluator(IndentedWriter writer)
        {
            writer.WriteLine("public readonly struct AutoChessGeneratedExecutionOutputRecord");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public readonly float Damage;");
            writer.WriteLine();
            writer.WriteLine("public AutoChessGeneratedExecutionOutputRecord(float damage)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Damage = damage;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
            writer.WriteLine();
            writer.WriteLine("public static class AutoChessGeneratedExecutionEvaluator");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public static bool TryEvaluateExecuteDamage(");
            writer.Indent++;
            writer.WriteLine("float baseValue,");
            writer.WriteLine("float maxValue,");
            writer.WriteLine("bool isClampMax,");
            writer.WriteLine("float baseDamage,");
            writer.WriteLine("float missingHealthCoefficient,");
            writer.WriteLine("float minDamage,");
            writer.WriteLine("float maxDamage,");
            writer.WriteLine("out AutoChessGeneratedExecutionOutputRecord output)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("output = default;");
            writer.WriteLine("if (baseValue <= 0f)");
            writer.Indent++;
            writer.WriteLine("return false;");
            writer.Indent--;
            writer.WriteLine();
            writer.WriteLine("var effectiveMaxValue = isClampMax ? maxValue : baseValue;");
            writer.WriteLine("var missingHealth = math.max(0f, effectiveMaxValue - baseValue);");
            writer.WriteLine("var clampedMaxDamage = math.max(minDamage, maxDamage);");
            writer.WriteLine("var damage = math.clamp(");
            writer.Indent++;
            writer.WriteLine("baseDamage + missingHealth * missingHealthCoefficient,");
            writer.WriteLine("minDamage,");
            writer.WriteLine("clampedMaxDamage);");
            writer.Indent--;
            writer.WriteLine("if (damage <= 0f)");
            writer.Indent++;
            writer.WriteLine("return false;");
            writer.Indent--;
            writer.WriteLine();
            writer.WriteLine("output = new AutoChessGeneratedExecutionOutputRecord(damage);");
            writer.WriteLine("return true;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteGeneratedUnitSpawnPlan(IndentedWriter writer)
        {
            writer.WriteLine("public readonly struct AutoChessGeneratedUnitSpawnPlan");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public readonly string Id;");
            writer.WriteLine("public readonly string DisplayName;");
            writer.WriteLine("public readonly string ArchetypeName;");
            writer.WriteLine("public readonly AutoChessTeam Team;");
            writer.WriteLine("public readonly int Slot;");
            writer.WriteLine("public readonly float Health;");
            writer.WriteLine("public readonly float Energy;");
            writer.WriteLine("public readonly int PrimaryAbilityCode;");
            writer.WriteLine("public readonly int FinisherAbilityCode;");
            writer.WriteLine("public readonly int ActiveAbilityCode;");
            writer.WriteLine("public readonly int ActiveCastInterval;");
            writer.WriteLine("public readonly int ActiveCastFrameOffset;");
            writer.WriteLine("public readonly float FinisherHealthThreshold;");
            writer.WriteLine("public readonly AutoChessTargetPolicy PrimaryTargetPolicy;");
            writer.WriteLine("public readonly AutoChessTargetPolicy FinisherTargetPolicy;");
            writer.WriteLine();
            writer.WriteLine("public AutoChessGeneratedUnitSpawnPlan(");
            writer.Indent++;
            writer.WriteLine("string id,");
            writer.WriteLine("string displayName,");
            writer.WriteLine("string archetypeName,");
            writer.WriteLine("AutoChessTeam team,");
            writer.WriteLine("int slot,");
            writer.WriteLine("float health,");
            writer.WriteLine("float energy,");
            writer.WriteLine("int primaryAbilityCode,");
            writer.WriteLine("int finisherAbilityCode,");
            writer.WriteLine("int activeAbilityCode,");
            writer.WriteLine("int activeCastInterval,");
            writer.WriteLine("int activeCastFrameOffset,");
            writer.WriteLine("float finisherHealthThreshold,");
            writer.WriteLine("AutoChessTargetPolicy primaryTargetPolicy,");
            writer.WriteLine("AutoChessTargetPolicy finisherTargetPolicy)");
            writer.Indent--;
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("Id = id ?? string.Empty;");
            writer.WriteLine("DisplayName = displayName ?? string.Empty;");
            writer.WriteLine("ArchetypeName = archetypeName ?? string.Empty;");
            writer.WriteLine("Team = team;");
            writer.WriteLine("Slot = slot;");
            writer.WriteLine("Health = health;");
            writer.WriteLine("Energy = energy;");
            writer.WriteLine("PrimaryAbilityCode = primaryAbilityCode;");
            writer.WriteLine("FinisherAbilityCode = finisherAbilityCode;");
            writer.WriteLine("ActiveAbilityCode = activeAbilityCode;");
            writer.WriteLine("ActiveCastInterval = activeCastInterval;");
            writer.WriteLine("ActiveCastFrameOffset = activeCastFrameOffset;");
            writer.WriteLine("FinisherHealthThreshold = finisherHealthThreshold;");
            writer.WriteLine("PrimaryTargetPolicy = primaryTargetPolicy;");
            writer.WriteLine("FinisherTargetPolicy = finisherTargetPolicy;");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteGeneratedConfig(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine("public static class AutoChessGeneratedConfig");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("public const string RoomIdPrefix = \"room-standard-duel-x\";");
            writer.WriteLine("public const string RoomDisplayName = \"标准双人自走棋对局\";");
            writer.WriteLine("public const string PlayerId = \"player-a\";");
            writer.WriteLine("public const string EnemyId = \"player-b\";");
            writer.WriteLine("public const string PlayerDisplayName = \"玩家A\";");
            writer.WriteLine("public const string EnemyDisplayName = \"玩家B\";");
            writer.WriteLine();
            writer.WriteLine($"public const int AttributeSetCombat = {model.AttributeSetCombat};");
            writer.WriteLine($"public const int AttributeHealth = {model.AttributeHealth};");
            writer.WriteLine($"public const int AttributeEnergy = {model.AttributeEnergy};");
            writer.WriteLine($"public const int AbilityPlayerAttack = {model.AbilityPlayerAttack};");
            writer.WriteLine($"public const int AbilityEnemyAttack = {model.AbilityEnemyAttack};");
            writer.WriteLine($"public const int AbilityPlayerExecute = {model.AbilityPlayerExecute};");
            writer.WriteLine($"public const int AbilityPlayerPoison = {model.AbilityPlayerPoison};");
            writer.WriteLine($"public const int GameplayEffectPlayerAttackDamage = {model.GameplayEffectPlayerAttackDamage};");
            writer.WriteLine($"public const int GameplayEffectEnemyAttackDamage = {model.GameplayEffectEnemyAttackDamage};");
            writer.WriteLine($"public const int GameplayEffectPlayerExecute = {model.GameplayEffectPlayerExecute};");
            writer.WriteLine($"public const int GameplayEffectPlayerPoison = {model.GameplayEffectPlayerPoison};");
            writer.WriteLine($"public const int GameplayEffectPoisonTickDamage = {model.GameplayEffectPoisonTickDamage};");
            writer.WriteLine($"public const int ExecutionCalculationExecuteDamage = {model.ExecutionCalculationExecuteDamage};");
            writer.WriteLine($"public const int ExecutionCalculationExecuteDamageOutput = {model.ExecutionCalculationExecuteDamageOutput};");
            writer.WriteLine($"public const int TagAttackCooldown = {model.TagAttackCooldown};");
            writer.WriteLine();
            WriteExecuteDamageCalculation(writer, model.ExecuteDamageCalculation);
            writer.WriteLine();
            writer.WriteLine("public static AutoChessGeneratedScenarioProfile ValidationScenario => new AutoChessGeneratedScenarioProfile(");
            writer.Indent++;
            writer.WriteLine($"{model.ValidationScenario.Scale},");
            writer.WriteLine($"{model.ValidationScenario.MaxTicks},");
            writer.WriteLine($"{model.ValidationScenario.PostVictoryFlushTicks},");
            writer.WriteLine($"{model.ValidationScenario.ProcessWarmupRuns},");
            writer.WriteLine($"{FloatLiteral(model.ValidationScenario.HealthMultiplier)},");
            writer.WriteLine($"{model.ValidationScenario.ExpectedWinner},");
            writer.WriteLine($"{model.ValidationScenario.MinDriverIssuedCommands},");
            writer.WriteLine($"{model.ValidationScenario.MinAttributeChanges},");
            writer.WriteLine($"{model.ValidationScenario.MinExecutionOutputs},");
            writer.WriteLine($"{model.ValidationScenario.MinCueRequests},");
            writer.WriteLine($"{model.ValidationScenario.MinActiveEffectSlots},");
            writer.WriteLine($"{model.ValidationScenario.MinPeriodTickDamageFacts},");
            writer.WriteLine($"{model.ValidationScenario.MinActiveMutationCommands},");
            writer.WriteLine($"{model.ValidationScenario.MinActiveMutationOwnerGroups},");
            writer.WriteLine($"{model.ValidationScenario.MaxActiveMutationEstimatedRandomLookups},");
            writer.WriteLine($"{model.ValidationScenario.MaxActiveMutationOwnerResourceLookups},");
            writer.WriteLine($"{model.ValidationScenario.MaxActiveMutationMigrationCarriers});");
            writer.Indent--;
            writer.WriteLine();
            WriteBaseUnitSpawnPlans(writer, model);
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteExecuteDamageCalculation(
            IndentedWriter writer,
            AutoChessDemoExecuteDamageCalculationModel row)
        {
            writer.WriteLine("public static AutoChessGeneratedExecuteDamageCalculation ExecuteDamageCalculation => new AutoChessGeneratedExecuteDamageCalculation(");
            writer.Indent++;
            writer.WriteLine($"{row.GameplayEffectCode},");
            writer.WriteLine($"{row.CalculationCode},");
            writer.WriteLine($"{row.OutputKey},");
            writer.WriteLine($"{row.HealthAttrSetCode},");
            writer.WriteLine($"{row.HealthAttrCode},");
            writer.WriteLine($"{FloatLiteral(row.BaseDamage)},");
            writer.WriteLine($"{FloatLiteral(row.MissingHealthCoefficient)},");
            writer.WriteLine($"{FloatLiteral(row.MinDamage)},");
            writer.WriteLine($"{FloatLiteral(row.MaxDamage)});");
            writer.Indent--;
        }

        private static void WriteBaseUnitSpawnPlans(IndentedWriter writer, AutoChessDemoConfigModel model)
        {
            writer.WriteLine($"public const int BaseUnitSpawnPlanCount = {model.BaseUnits.Count};");
            writer.WriteLine();
            writer.WriteLine("public static AutoChessGeneratedUnitSpawnPlan GetBaseUnitSpawnPlan(int index)");
            writer.WriteLine("{");
            writer.Indent++;
            writer.WriteLine("return index switch");
            writer.WriteLine("{");
            writer.Indent++;
            for (var i = 0; i < model.BaseUnits.Count; i++)
            {
                writer.WriteLine($"{i} =>");
                writer.Indent++;
                WriteUnit(writer, model.BaseUnits[i]);
                writer.Indent--;
            }
            writer.WriteLine("_ => throw new ArgumentOutOfRangeException(");
            writer.Indent++;
            writer.WriteLine("nameof(index),");
            writer.WriteLine("index,");
            writer.WriteLine("\"Unknown AutoChess base unit spawn plan index.\"),");
            writer.Indent--;
            writer.Indent--;
            writer.WriteLine("};");
            writer.Indent--;
            writer.WriteLine("}");
        }

        private static void WriteUnit(IndentedWriter writer, AutoChessDemoUnitModel unit)
        {
            writer.WriteLine("new AutoChessGeneratedUnitSpawnPlan(");
            writer.Indent++;
            writer.WriteLine($"{StringLiteral(unit.Id)},");
            writer.WriteLine($"{StringLiteral(unit.DisplayName)},");
            writer.WriteLine($"{StringLiteral(unit.ArchetypeName)},");
            writer.WriteLine($"{unit.Team},");
            writer.WriteLine($"{unit.Slot.ToString(CultureInfo.InvariantCulture)},");
            writer.WriteLine($"{FloatLiteral(unit.Health)},");
            writer.WriteLine($"{FloatLiteral(unit.Energy)},");
            writer.WriteLine($"{unit.PrimaryAbilityCode},");
            writer.WriteLine($"{unit.FinisherAbilityCode},");
            writer.WriteLine($"{unit.ActiveAbilityCode},");
            writer.WriteLine($"{unit.ActiveCastInterval.ToString(CultureInfo.InvariantCulture)},");
            writer.WriteLine($"{unit.ActiveCastFrameOffset.ToString(CultureInfo.InvariantCulture)},");
            writer.WriteLine($"{FloatLiteral(unit.FinisherHealthThreshold)},");
            writer.WriteLine($"{unit.PrimaryTargetPolicy},");
            writer.WriteLine($"{unit.FinisherTargetPolicy}),");
            writer.Indent--;
        }

        private static string FloatLiteral(float value)
        {
            return value.ToString("0.########", CultureInfo.InvariantCulture) + "f";
        }

        private static string StringLiteral(string value)
        {
            if (value == null)
                return "string.Empty";

            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n") + "\"";
        }

        private static void EnsureUnityMeta(string path)
        {
            var metaPath = path + ".meta";
            if (File.Exists(metaPath))
                return;

            File.WriteAllText(
                metaPath,
                "fileFormatVersion: 2\n"
                + "guid: " + CreateGuid(path) + "\n"
                + "MonoImporter:\n"
                + "  externalObjects: {}\n"
                + "  serializedVersion: 2\n"
                + "  defaultReferences: []\n"
                + "  executionOrder: 0\n"
                + "  icon: {instanceID: 0}\n"
                + "  userData: \n"
                + "  assetBundleName: \n"
                + "  assetBundleVariant: \n");
        }

        private static string CreateGuid(string path)
        {
            unchecked
            {
                var hash = 17;
                for (var i = 0; i < path.Length; i++)
                    hash = hash * 31 + char.ToLowerInvariant(path[i]);

                var value = Math.Abs(hash).ToString("x8", CultureInfo.InvariantCulture);
                return value + value + value + value;
            }
        }
    }
}
