// <auto-generated/>
using System;
using GAS.Runtime;
using Unity.Collections;
using Unity.Entities;

namespace GAS.AutoChessDemo
{
    /// <summary>
    /// 保存 generated AutoChess 验证场景阈值。
    /// </summary>
    public readonly struct AutoChessGeneratedScenarioProfile
    {
        public readonly int Scale;
        public readonly int MaxTicks;
        public readonly float HealthMultiplier;
        public readonly AutoChessTeam ExpectedWinner;
        public readonly int MinAcceptedCommands;
        public readonly int MinAttributeChanges;
        public readonly int MinExecutionOutputs;
        public readonly int MinCueRequests;
        public readonly int MinActiveEffectSlots;
        public readonly int MinPeriodTickDamageFacts;
        public readonly int MinActiveMutationCommands;
        public readonly int MinActiveMutationOwnerGroups;
        public readonly int MaxActiveMutationEstimatedRandomLookups;
        public readonly int MaxActiveMutationOwnerResourceLookups;
        public readonly int MaxActiveMutationMigrationCarriers;

        /// <summary>
        /// 创建一个 generated 验证场景 profile。
        /// </summary>
        public AutoChessGeneratedScenarioProfile(
            int scale,
            int maxTicks,
            float healthMultiplier,
            AutoChessTeam expectedWinner,
            int minAcceptedCommands,
            int minAttributeChanges,
            int minExecutionOutputs,
            int minCueRequests,
            int minActiveEffectSlots,
            int minPeriodTickDamageFacts,
            int minActiveMutationCommands,
            int minActiveMutationOwnerGroups,
            int maxActiveMutationEstimatedRandomLookups,
            int maxActiveMutationOwnerResourceLookups,
            int maxActiveMutationMigrationCarriers)
        {
            Scale = scale;
            MaxTicks = maxTicks;
            HealthMultiplier = healthMultiplier;
            ExpectedWinner = expectedWinner;
            MinAcceptedCommands = minAcceptedCommands;
            MinAttributeChanges = minAttributeChanges;
            MinExecutionOutputs = minExecutionOutputs;
            MinCueRequests = minCueRequests;
            MinActiveEffectSlots = minActiveEffectSlots;
            MinPeriodTickDamageFacts = minPeriodTickDamageFacts;
            MinActiveMutationCommands = minActiveMutationCommands;
            MinActiveMutationOwnerGroups = minActiveMutationOwnerGroups;
            MaxActiveMutationEstimatedRandomLookups = maxActiveMutationEstimatedRandomLookups;
            MaxActiveMutationOwnerResourceLookups = maxActiveMutationOwnerResourceLookups;
            MaxActiveMutationMigrationCarriers = maxActiveMutationMigrationCarriers;
        }
    }

    /// <summary>
    /// 保存 generated AutoChess 单位生成参数。
    /// </summary>
    public readonly struct AutoChessGeneratedUnitSpawnPlan
    {
        public readonly string Id;
        public readonly string DisplayName;
        public readonly string ArchetypeName;
        public readonly AutoChessTeam Team;
        public readonly int Slot;
        public readonly float Health;
        public readonly float Energy;
        public readonly int PrimaryAbilityCode;
        public readonly int FinisherAbilityCode;
        public readonly int ActiveAbilityCode;
        public readonly int ActiveCastInterval;
        public readonly int ActiveCastFrameOffset;
        public readonly float FinisherHealthThreshold;
        public readonly AutoChessTargetPolicy PrimaryTargetPolicy;
        public readonly AutoChessTargetPolicy FinisherTargetPolicy;

        /// <summary>
        /// 创建一个 generated 单位 spawn plan。
        /// </summary>
        public AutoChessGeneratedUnitSpawnPlan(
            string id,
            string displayName,
            string archetypeName,
            AutoChessTeam team,
            int slot,
            float health,
            float energy,
            int primaryAbilityCode,
            int finisherAbilityCode,
            int activeAbilityCode,
            int activeCastInterval,
            int activeCastFrameOffset,
            float finisherHealthThreshold,
            AutoChessTargetPolicy primaryTargetPolicy,
            AutoChessTargetPolicy finisherTargetPolicy)
        {
            Id = id ?? string.Empty;
            DisplayName = displayName ?? string.Empty;
            ArchetypeName = archetypeName ?? string.Empty;
            Team = team;
            Slot = slot;
            Health = health;
            Energy = energy;
            PrimaryAbilityCode = primaryAbilityCode;
            FinisherAbilityCode = finisherAbilityCode;
            ActiveAbilityCode = activeAbilityCode;
            ActiveCastInterval = activeCastInterval;
            ActiveCastFrameOffset = activeCastFrameOffset;
            FinisherHealthThreshold = finisherHealthThreshold;
            PrimaryTargetPolicy = primaryTargetPolicy;
            FinisherTargetPolicy = finisherTargetPolicy;
        }
    }

    /// <summary>
    /// 由 Luban 权威表生成 AutoChess Runtime v1 Catalog pure data。
    /// </summary>
    internal static class AutoChessGeneratedDefinitionCatalog
    {
        /// <summary>
        /// 两遍物化 generated source，并返回独立冻结的 Stage-B 期望身份。
        /// </summary>
        internal static BlobAssetReference<GasDefinitionCatalogBlob> Build(
            Allocator allocator,
            out GasCatalogValidationExpectation expectation)
        {
            return AutoChessDefinitionCatalogCompiler.Build(CreateSource(), allocator, out expectation);
        }

        /// <summary>
        /// 创建不含手写玩法常量的 generated Catalog source。
        /// </summary>
        private static AutoChessDefinitionCatalogSource CreateSource()
        {
            return new AutoChessDefinitionCatalogSource
            {
                Attributes = CreateAttributes(),
                AbilityIndex = CreateAbilityIndex(),
                Abilities = CreateAbilities(),
                GameplayEffectIndex = CreateGameplayEffectIndex(),
                GameplayEffects = CreateGameplayEffects(),
                Modifiers = CreateModifiers(),
                DirectEffectProgramNodes = CreateDirectEffectProgramNodes(),
                CueReferences = CreateCueReferences(),
                ValueViews = CreateValueViews(),
                EvaluatorInstructions = CreateEvaluatorInstructions(),
                TargetDataDescriptors = CreateTargetDataDescriptors(),
                EffectContextFieldDescriptors = CreateEffectContextFieldDescriptors(),
            };
        }

        /// <summary>
        /// 创建按 Attribute ID 排序的 dense layout。
        /// </summary>
        private static GasAttributeLayoutEntryBlob[] CreateAttributes()
        {
            return new[]
            {
                new GasAttributeLayoutEntryBlob
                {
                    AttributeId = 1,
                    LayoutIndex = 0,
                    DomainRole = (GasAttributeDomainRole)1,
                    DefaultValue = 100f,
                    MinimumValue = 0f,
                    MaximumValue = 99999f,
                    ClampMinimum = 1,
                    ClampMaximum = 1,
                },
                new GasAttributeLayoutEntryBlob
                {
                    AttributeId = 2,
                    LayoutIndex = 1,
                    DomainRole = (GasAttributeDomainRole)0,
                    DefaultValue = 0f,
                    MinimumValue = 0f,
                    MaximumValue = 99999f,
                    ClampMinimum = 1,
                    ClampMaximum = 1,
                },
            };
        }

        /// <summary>
        /// 创建稳定 Definition 索引。
        /// </summary>
        private static GasDefinitionIndexEntry[] CreateAbilityIndex()
        {
            return new[]
            {
                new GasDefinitionIndexEntry { DefinitionId = 9101, DefinitionIndex = 0 },
                new GasDefinitionIndexEntry { DefinitionId = 9102, DefinitionIndex = 1 },
                new GasDefinitionIndexEntry { DefinitionId = 9103, DefinitionIndex = 2 },
                new GasDefinitionIndexEntry { DefinitionId = 9104, DefinitionIndex = 3 },
            };
        }

        /// <summary>
        /// 创建稳定 Definition 索引。
        /// </summary>
        private static GasDefinitionIndexEntry[] CreateGameplayEffectIndex()
        {
            return new[]
            {
                new GasDefinitionIndexEntry { DefinitionId = 9201, DefinitionIndex = 0 },
                new GasDefinitionIndexEntry { DefinitionId = 9202, DefinitionIndex = 1 },
                new GasDefinitionIndexEntry { DefinitionId = 9203, DefinitionIndex = 2 },
                new GasDefinitionIndexEntry { DefinitionId = 9204, DefinitionIndex = 3 },
                new GasDefinitionIndexEntry { DefinitionId = 9207, DefinitionIndex = 4 },
            };
        }

        /// <summary>
        /// 创建全部 Ability definitions。
        /// </summary>
        private static GasAbilityDefinitionBlob[] CreateAbilities()
        {
            return new[]
            {
                CreateAbility9101(),
                CreateAbility9102(),
                CreateAbility9103(),
                CreateAbility9104(),
            };
        }

        /// <summary>
        /// 创建 Luban Ability 9101 的 Runtime v1 definition。
        /// </summary>
        private static GasAbilityDefinitionBlob CreateAbility9101()
        {
            return new GasAbilityDefinitionBlob
            {
                DefinitionId = 9101,
                Level = 1,
                MaxConcurrentActivations = 1,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                DirectEffectProgramRange = Range(0, 1),
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 0,
                    MaximumDirectProgramNodeCount = 1,
                    MaximumDirectProgramOutputCount = 1,
                    MaximumCueCount = 0,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 0,
                    MaximumTargetDataCount = 0,
                    MaximumEffectContextFieldCount = 0,
                },
            };
        }

        /// <summary>
        /// 创建 Luban Ability 9102 的 Runtime v1 definition。
        /// </summary>
        private static GasAbilityDefinitionBlob CreateAbility9102()
        {
            return new GasAbilityDefinitionBlob
            {
                DefinitionId = 9102,
                Level = 1,
                MaxConcurrentActivations = 1,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                DirectEffectProgramRange = Range(1, 1),
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 0,
                    MaximumDirectProgramNodeCount = 1,
                    MaximumDirectProgramOutputCount = 1,
                    MaximumCueCount = 0,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 0,
                    MaximumTargetDataCount = 0,
                    MaximumEffectContextFieldCount = 0,
                },
            };
        }

        /// <summary>
        /// 创建 Luban Ability 9103 的 Runtime v1 definition。
        /// </summary>
        private static GasAbilityDefinitionBlob CreateAbility9103()
        {
            return new GasAbilityDefinitionBlob
            {
                DefinitionId = 9103,
                Level = 1,
                MaxConcurrentActivations = 1,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                DirectEffectProgramRange = Range(2, 1),
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 0,
                    MaximumDirectProgramNodeCount = 1,
                    MaximumDirectProgramOutputCount = 1,
                    MaximumCueCount = 0,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 0,
                    MaximumTargetDataCount = 0,
                    MaximumEffectContextFieldCount = 0,
                },
            };
        }

        /// <summary>
        /// 创建 Luban Ability 9104 的 Runtime v1 definition。
        /// </summary>
        private static GasAbilityDefinitionBlob CreateAbility9104()
        {
            return new GasAbilityDefinitionBlob
            {
                DefinitionId = 9104,
                Level = 1,
                MaxConcurrentActivations = 1,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                DirectEffectProgramRange = Range(3, 1),
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 0,
                    MaximumDirectProgramNodeCount = 1,
                    MaximumDirectProgramOutputCount = 1,
                    MaximumCueCount = 0,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 0,
                    MaximumTargetDataCount = 0,
                    MaximumEffectContextFieldCount = 0,
                },
            };
        }

        /// <summary>
        /// 创建 root 与 period child 的完整 GameplayEffect 闭包。
        /// </summary>
        private static GasGameplayEffectDefinitionBlob[] CreateGameplayEffects()
        {
            return new[]
            {
                CreateEffect9201(),
                CreateEffect9202(),
                CreateEffect9203(),
                CreateEffect9204(),
                CreateEffect9207(),
            };
        }

        /// <summary>
        /// 创建 Luban GameplayEffect 9201 的 Runtime v1 definition。
        /// </summary>
        private static GasGameplayEffectDefinitionBlob CreateEffect9201()
        {
            return new GasGameplayEffectDefinitionBlob
            {
                DefinitionId = 9201,
                Lifetime = GasEffectLifetimePolicy.Instant,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                ModifierRange = Range(0, 1),
                CueRange = Range(0, 1),
                ValueViewRange = Range(0, 0),
                EvaluatorProgramRange = Range(0, 1),
                TargetDataRange = Range(0, 1),
                EffectContextFieldRange = Range(0, 3),
                RequiredValueViews = GasAttributeValueViewMask.None,
                DurationTicks = 0,
                PeriodTicks = 0,
                StackLimit = 0,
                StackKey = GasStackKeyFields.None,
                StackPolicy = GasStackPolicy.None,
                StackPayloadPolicy = GasStackPayloadPolicy.None,
                StackLimitApplicationPolicy = GasStackLimitApplicationPolicy.None,
                DurationRefreshPolicy = GasDurationRefreshPolicy.Never,
                PeriodResetPolicy = GasPeriodResetPolicy.Never,
                ExpiryPolicy = GasExpiryPolicy.Remove,
                ExpiryPeriodPolicy = GasExpiryPeriodPolicy.Stop,
                ExpirySameTickPolicy = GasExpirySameTickPolicy.ExpiryBeforePeriodDue,
                InhibitTimePolicy = GasInhibitTimePolicy.DurationContinues,
                InhibitedPeriodPolicy = GasInhibitedPeriodPolicy.None,
                MissedPeriodPolicy = GasMissedPeriodPolicy.SkipNoCatchUp,
                ExecuteOnApplication = 0,
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 1,
                    MaximumDirectProgramNodeCount = 0,
                    MaximumDirectProgramOutputCount = 0,
                    MaximumCueCount = 1,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 1,
                    MaximumTargetDataCount = 1,
                    MaximumEffectContextFieldCount = 3,
                },
            };
        }

        /// <summary>
        /// 创建 Luban GameplayEffect 9202 的 Runtime v1 definition。
        /// </summary>
        private static GasGameplayEffectDefinitionBlob CreateEffect9202()
        {
            return new GasGameplayEffectDefinitionBlob
            {
                DefinitionId = 9202,
                Lifetime = GasEffectLifetimePolicy.Instant,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                ModifierRange = Range(1, 1),
                CueRange = Range(1, 1),
                ValueViewRange = Range(0, 0),
                EvaluatorProgramRange = Range(1, 1),
                TargetDataRange = Range(1, 1),
                EffectContextFieldRange = Range(3, 3),
                RequiredValueViews = GasAttributeValueViewMask.None,
                DurationTicks = 0,
                PeriodTicks = 0,
                StackLimit = 0,
                StackKey = GasStackKeyFields.None,
                StackPolicy = GasStackPolicy.None,
                StackPayloadPolicy = GasStackPayloadPolicy.None,
                StackLimitApplicationPolicy = GasStackLimitApplicationPolicy.None,
                DurationRefreshPolicy = GasDurationRefreshPolicy.Never,
                PeriodResetPolicy = GasPeriodResetPolicy.Never,
                ExpiryPolicy = GasExpiryPolicy.Remove,
                ExpiryPeriodPolicy = GasExpiryPeriodPolicy.Stop,
                ExpirySameTickPolicy = GasExpirySameTickPolicy.ExpiryBeforePeriodDue,
                InhibitTimePolicy = GasInhibitTimePolicy.DurationContinues,
                InhibitedPeriodPolicy = GasInhibitedPeriodPolicy.None,
                MissedPeriodPolicy = GasMissedPeriodPolicy.SkipNoCatchUp,
                ExecuteOnApplication = 0,
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 1,
                    MaximumDirectProgramNodeCount = 0,
                    MaximumDirectProgramOutputCount = 0,
                    MaximumCueCount = 1,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 1,
                    MaximumTargetDataCount = 1,
                    MaximumEffectContextFieldCount = 3,
                },
            };
        }

        /// <summary>
        /// 创建 Luban GameplayEffect 9203 的 Runtime v1 definition。
        /// </summary>
        private static GasGameplayEffectDefinitionBlob CreateEffect9203()
        {
            return new GasGameplayEffectDefinitionBlob
            {
                DefinitionId = 9203,
                Lifetime = GasEffectLifetimePolicy.Duration,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                ModifierRange = Range(2, 1),
                CueRange = Range(2, 1),
                ValueViewRange = Range(0, 0),
                EvaluatorProgramRange = Range(2, 1),
                TargetDataRange = Range(2, 1),
                EffectContextFieldRange = Range(6, 3),
                RequiredValueViews = GasAttributeValueViewMask.None,
                DurationTicks = 8,
                PeriodTicks = 2,
                StackLimit = 3,
                StackKey = GasStackKeyFields.Definition | GasStackKeyFields.TargetAsc | GasStackKeyFields.SourceAsc,
                StackPolicy = GasStackPolicy.AggregateBySource,
                StackPayloadPolicy = GasStackPayloadPolicy.ReplaceLatestPayloadAndProvenance,
                StackLimitApplicationPolicy = GasStackLimitApplicationPolicy.AcceptAndKeepLimit,
                DurationRefreshPolicy = GasDurationRefreshPolicy.OnSuccessfulApplication,
                PeriodResetPolicy = GasPeriodResetPolicy.OnSuccessfulApplication,
                ExpiryPolicy = GasExpiryPolicy.Remove,
                ExpiryPeriodPolicy = GasExpiryPeriodPolicy.Stop,
                ExpirySameTickPolicy = GasExpirySameTickPolicy.PeriodDueBeforeExpiry,
                InhibitTimePolicy = GasInhibitTimePolicy.DurationContinues,
                InhibitedPeriodPolicy = GasInhibitedPeriodPolicy.SkipExecution,
                MissedPeriodPolicy = GasMissedPeriodPolicy.SkipNoCatchUp,
                ExecuteOnApplication = 0,
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 1,
                    MaximumDirectProgramNodeCount = 0,
                    MaximumDirectProgramOutputCount = 0,
                    MaximumCueCount = 1,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 1,
                    MaximumTargetDataCount = 1,
                    MaximumEffectContextFieldCount = 3,
                },
            };
        }

        /// <summary>
        /// 创建 Luban GameplayEffect 9204 的 Runtime v1 definition。
        /// </summary>
        private static GasGameplayEffectDefinitionBlob CreateEffect9204()
        {
            return new GasGameplayEffectDefinitionBlob
            {
                DefinitionId = 9204,
                Lifetime = GasEffectLifetimePolicy.Instant,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                ModifierRange = Range(3, 1),
                CueRange = Range(3, 1),
                ValueViewRange = Range(0, 0),
                EvaluatorProgramRange = Range(3, 1),
                TargetDataRange = Range(3, 1),
                EffectContextFieldRange = Range(9, 3),
                RequiredValueViews = GasAttributeValueViewMask.None,
                DurationTicks = 0,
                PeriodTicks = 0,
                StackLimit = 0,
                StackKey = GasStackKeyFields.None,
                StackPolicy = GasStackPolicy.None,
                StackPayloadPolicy = GasStackPayloadPolicy.None,
                StackLimitApplicationPolicy = GasStackLimitApplicationPolicy.None,
                DurationRefreshPolicy = GasDurationRefreshPolicy.Never,
                PeriodResetPolicy = GasPeriodResetPolicy.Never,
                ExpiryPolicy = GasExpiryPolicy.Remove,
                ExpiryPeriodPolicy = GasExpiryPeriodPolicy.Stop,
                ExpirySameTickPolicy = GasExpirySameTickPolicy.ExpiryBeforePeriodDue,
                InhibitTimePolicy = GasInhibitTimePolicy.DurationContinues,
                InhibitedPeriodPolicy = GasInhibitedPeriodPolicy.None,
                MissedPeriodPolicy = GasMissedPeriodPolicy.SkipNoCatchUp,
                ExecuteOnApplication = 0,
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 1,
                    MaximumDirectProgramNodeCount = 0,
                    MaximumDirectProgramOutputCount = 0,
                    MaximumCueCount = 1,
                    MaximumValueViewCount = 0,
                    MaximumEvaluatorInstructionCount = 1,
                    MaximumTargetDataCount = 1,
                    MaximumEffectContextFieldCount = 3,
                },
            };
        }

        /// <summary>
        /// 创建 Luban GameplayEffect 9207 的 Runtime v1 definition。
        /// </summary>
        private static GasGameplayEffectDefinitionBlob CreateEffect9207()
        {
            return new GasGameplayEffectDefinitionBlob
            {
                DefinitionId = 9207,
                Lifetime = GasEffectLifetimePolicy.InstantExecution,
                TargetPolicy = new GasTargetPolicyBlob
                {
                    LogicalTarget = (GasLogicalTargetPolicy)2,
                    Avatar = (GasAvatarTargetPolicy)2,
                    Spatial = (GasSpatialTargetPolicy)1,
                    Life = (GasTargetLifePolicy)1,
                },
                ModifierRange = Range(4, 1),
                CueRange = Range(4, 1),
                ValueViewRange = Range(0, 3),
                EvaluatorProgramRange = Range(4, 13),
                TargetDataRange = Range(4, 1),
                EffectContextFieldRange = Range(12, 3),
                RequiredValueViews = GasAttributeValueViewMask.Base | GasAttributeValueViewMask.Current | GasAttributeValueViewMask.DefinitionMaxValue,
                DurationTicks = 0,
                PeriodTicks = 0,
                StackLimit = 0,
                StackKey = GasStackKeyFields.None,
                StackPolicy = GasStackPolicy.None,
                StackPayloadPolicy = GasStackPayloadPolicy.None,
                StackLimitApplicationPolicy = GasStackLimitApplicationPolicy.None,
                DurationRefreshPolicy = GasDurationRefreshPolicy.Never,
                PeriodResetPolicy = GasPeriodResetPolicy.Never,
                ExpiryPolicy = GasExpiryPolicy.Remove,
                ExpiryPeriodPolicy = GasExpiryPeriodPolicy.Stop,
                ExpirySameTickPolicy = GasExpirySameTickPolicy.ExpiryBeforePeriodDue,
                InhibitTimePolicy = GasInhibitTimePolicy.DurationContinues,
                InhibitedPeriodPolicy = GasInhibitedPeriodPolicy.None,
                MissedPeriodPolicy = GasMissedPeriodPolicy.SkipNoCatchUp,
                ExecuteOnApplication = 0,
                Maxima = new GasDefinitionMaxima
                {
                    MaximumTargetCount = 1,
                    MaximumPlannedApplicationCount = 1,
                    MaximumCaptureDescriptorCount = 0,
                    MaximumModifierCount = 1,
                    MaximumDirectProgramNodeCount = 0,
                    MaximumDirectProgramOutputCount = 0,
                    MaximumCueCount = 1,
                    MaximumValueViewCount = 3,
                    MaximumEvaluatorInstructionCount = 13,
                    MaximumTargetDataCount = 1,
                    MaximumEffectContextFieldCount = 3,
                },
            };
        }

        /// <summary>
        /// 创建一个 generated Catalog 半开区间。
        /// </summary>
        private static GasCatalogRange Range(int start, int count)
        {
            return new GasCatalogRange { Start = start, Count = count };
        }

        /// <summary>
        /// 创建 flat Modifier definitions。
        /// </summary>
        private static GasModifierDefinitionBlob[] CreateModifiers()
        {
            return new GasModifierDefinitionBlob[]
            {
                new GasModifierDefinitionBlob
                {
                    AttributeLayoutIndex = 0,
                    Operation = GasModifierOperation.Add,
                    EvaluatorProgramRange = Range(0, 1),
                },
                new GasModifierDefinitionBlob
                {
                    AttributeLayoutIndex = 0,
                    Operation = GasModifierOperation.Add,
                    EvaluatorProgramRange = Range(1, 1),
                },
                new GasModifierDefinitionBlob
                {
                    AttributeLayoutIndex = 0,
                    Operation = GasModifierOperation.Add,
                    EvaluatorProgramRange = Range(2, 1),
                },
                new GasModifierDefinitionBlob
                {
                    AttributeLayoutIndex = 0,
                    Operation = GasModifierOperation.Add,
                    EvaluatorProgramRange = Range(3, 1),
                },
                new GasModifierDefinitionBlob
                {
                    AttributeLayoutIndex = 0,
                    Operation = GasModifierOperation.Add,
                    EvaluatorProgramRange = Range(4, 13),
                },
            };
        }

        /// <summary>
        /// 创建 Ability direct-effect program nodes。
        /// </summary>
        private static GasDirectEffectProgramNodeBlob[] CreateDirectEffectProgramNodes()
        {
            return new GasDirectEffectProgramNodeBlob[]
            {
                new GasDirectEffectProgramNodeBlob { NodeOrdinal = 0, EffectDefinitionId = 9201, MaximumTargetCount = 1, MaximumOutputCount = 1 },
                new GasDirectEffectProgramNodeBlob { NodeOrdinal = 0, EffectDefinitionId = 9202, MaximumTargetCount = 1, MaximumOutputCount = 1 },
                new GasDirectEffectProgramNodeBlob { NodeOrdinal = 0, EffectDefinitionId = 9207, MaximumTargetCount = 1, MaximumOutputCount = 1 },
                new GasDirectEffectProgramNodeBlob { NodeOrdinal = 0, EffectDefinitionId = 9203, MaximumTargetCount = 1, MaximumOutputCount = 1 },
            };
        }

        /// <summary>
        /// 创建按 definition 分段的 Cue references。
        /// </summary>
        private static GasCueReferenceBlob[] CreateCueReferences()
        {
            return new GasCueReferenceBlob[]
            {
                new GasCueReferenceBlob { CueDefinitionId = 9301, CueDefinitionOrdinal = 0, Phases = GasCuePhaseFlags.Executed },
                new GasCueReferenceBlob { CueDefinitionId = 9301, CueDefinitionOrdinal = 0, Phases = GasCuePhaseFlags.Executed },
                new GasCueReferenceBlob { CueDefinitionId = 9301, CueDefinitionOrdinal = 0, Phases = GasCuePhaseFlags.OnActive },
                new GasCueReferenceBlob { CueDefinitionId = 9301, CueDefinitionOrdinal = 0, Phases = GasCuePhaseFlags.Executed },
                new GasCueReferenceBlob { CueDefinitionId = 9301, CueDefinitionOrdinal = 0, Phases = GasCuePhaseFlags.Executed },
            };
        }

        /// <summary>
        /// 创建 evaluator ValueView descriptors。
        /// </summary>
        private static GasValueViewDescriptorBlob[] CreateValueViews()
        {
            return new GasValueViewDescriptorBlob[]
            {
                new GasValueViewDescriptorBlob { AttributeLayoutIndex = 0, ValueView = GasAttributeValueView.Base },
                new GasValueViewDescriptorBlob { AttributeLayoutIndex = 0, ValueView = GasAttributeValueView.Current },
                new GasValueViewDescriptorBlob { AttributeLayoutIndex = 0, ValueView = GasAttributeValueView.DefinitionMaxValue },
            };
        }

        /// <summary>
        /// 创建 canonical postfix evaluator instructions。
        /// </summary>
        private static GasEvaluatorInstructionBlob[] CreateEvaluatorInstructions()
        {
            return new GasEvaluatorInstructionBlob[]
            {
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = -12f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = -8f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = -1f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = -1f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushValueView,
                    OperandIndex = 2,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushValueView,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.Subtract,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = 0f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.Maximum,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = 0.5f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.Multiply,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = 16f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.Add,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = 12f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.PushConstant,
                    ConstantValue = 42f,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.Clamp,
                },
                new GasEvaluatorInstructionBlob
                {
                    Opcode = GasEvaluatorOpcode.Negate,
                },
            };
        }

        /// <summary>
        /// 创建每个 Effect 的 StableAsc TargetData descriptor。
        /// </summary>
        private static GasTargetDataDescriptorBlob[] CreateTargetDataDescriptors()
        {
            return new GasTargetDataDescriptorBlob[]
            {
                new GasTargetDataDescriptorBlob { Variant = GasTargetDataVariant.StableAsc, FieldOrdinal = 0, Required = 1 },
                new GasTargetDataDescriptorBlob { Variant = GasTargetDataVariant.StableAsc, FieldOrdinal = 0, Required = 1 },
                new GasTargetDataDescriptorBlob { Variant = GasTargetDataVariant.StableAsc, FieldOrdinal = 0, Required = 1 },
                new GasTargetDataDescriptorBlob { Variant = GasTargetDataVariant.StableAsc, FieldOrdinal = 0, Required = 1 },
                new GasTargetDataDescriptorBlob { Variant = GasTargetDataVariant.StableAsc, FieldOrdinal = 0, Required = 1 },
            };
        }

        /// <summary>
        /// 创建每个 Effect 的必需 context fields。
        /// </summary>
        private static GasEffectContextFieldDescriptorBlob[] CreateEffectContextFieldDescriptors()
        {
            return new GasEffectContextFieldDescriptorBlob[]
            {
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.CausalityId, FieldOrdinal = 0, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.SourceAvatarBindingGeneration, FieldOrdinal = 1, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.TargetAvatarBindingGeneration, FieldOrdinal = 2, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.CausalityId, FieldOrdinal = 0, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.SourceAvatarBindingGeneration, FieldOrdinal = 1, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.TargetAvatarBindingGeneration, FieldOrdinal = 2, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.CausalityId, FieldOrdinal = 0, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.SourceAvatarBindingGeneration, FieldOrdinal = 1, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.TargetAvatarBindingGeneration, FieldOrdinal = 2, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.CausalityId, FieldOrdinal = 0, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.SourceAvatarBindingGeneration, FieldOrdinal = 1, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.TargetAvatarBindingGeneration, FieldOrdinal = 2, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.CausalityId, FieldOrdinal = 0, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.SourceAvatarBindingGeneration, FieldOrdinal = 1, Required = 1 },
                new GasEffectContextFieldDescriptorBlob { Field = GasEffectContextFieldKind.TargetAvatarBindingGeneration, FieldOrdinal = 2, Required = 1 },
            };
        }
    }

    /// <summary>
    /// 暴露 AutoChess generated 稳定 ID 与场景数据。
    /// </summary>
    public static class AutoChessGeneratedConfig
    {
        public const string RoomIdPrefix = "room-standard-duel-x";
        public const string RoomDisplayName = "标准双人自走棋对局";
        public const string PlayerId = "player-a";
        public const string EnemyId = "player-b";
        public const string PlayerDisplayName = "玩家A";
        public const string EnemyDisplayName = "玩家B";

        public const int AttributeSetCombat = 9001;
        public const int AttributeHealth = 1;
        public const int AttributeEnergy = 2;
        public const int AbilityPlayerAttack = 9101;
        public const int AbilityEnemyAttack = 9102;
        public const int AbilityPlayerExecute = 9103;
        public const int AbilityPlayerPoison = 9104;
        public const int GameplayEffectPlayerAttackDamage = 9201;
        public const int GameplayEffectEnemyAttackDamage = 9202;
        public const int GameplayEffectPlayerExecute = 9207;
        public const int GameplayEffectPlayerPoison = 9203;

        /// <summary>
        /// 返回 generated 验证场景阈值。
        /// </summary>
        public static AutoChessGeneratedScenarioProfile ValidationScenario => new AutoChessGeneratedScenarioProfile(
            50,
            96,
            1f,
            AutoChessTeam.Player,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            0,
            0,
            0);

        public const int BaseUnitSpawnPlanCount = 4;

        /// <summary>
        /// 按稳定索引返回 generated 单位模板。
        /// </summary>
        public static AutoChessGeneratedUnitSpawnPlan GetBaseUnitSpawnPlan(int index)
        {
            return index switch
            {
                0 =>
                    new AutoChessGeneratedUnitSpawnPlan(
                        "player-vanguard",
                        "霜卫先锋",
                        "前排战士",
                        AutoChessTeam.Player,
                        0,
                        72f,
                        8f,
                        9101,
                        9103,
                        9104,
                        3,
                        0,
                        44f,
                        AutoChessTargetPolicy.Frontline,
                        AutoChessTargetPolicy.LowestHealth),
                1 =>
                    new AutoChessGeneratedUnitSpawnPlan(
                        "player-ranger",
                        "游侠射手",
                        "后排射手",
                        AutoChessTeam.Player,
                        1,
                        54f,
                        8f,
                        9101,
                        9103,
                        9104,
                        3,
                        1,
                        44f,
                        AutoChessTargetPolicy.LowestHealth,
                        AutoChessTargetPolicy.LowestHealth),
                2 =>
                    new AutoChessGeneratedUnitSpawnPlan(
                        "enemy-brute",
                        "荒原斗士",
                        "前排斗士",
                        AutoChessTeam.Enemy,
                        0,
                        48f,
                        8f,
                        9102,
                        0,
                        0,
                        0,
                        0,
                        0f,
                        AutoChessTargetPolicy.Frontline,
                        AutoChessTargetPolicy.Frontline),
                3 =>
                    new AutoChessGeneratedUnitSpawnPlan(
                        "enemy-caster",
                        "秘术术士",
                        "后排法师",
                        AutoChessTeam.Enemy,
                        1,
                        42f,
                        8f,
                        9102,
                        0,
                        0,
                        0,
                        0,
                        0f,
                        AutoChessTargetPolicy.Frontline,
                        AutoChessTargetPolicy.Frontline),
                _ => throw new ArgumentOutOfRangeException(nameof(index), index, "Unknown AutoChess base unit spawn plan index."),
            };
        }
    }
}
